### ISSUE TITLE
Nest and unnest drops interval with less than 2 observations

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/tsibble#103]
Related: https://github.com/tidyverts/fable/issues/120

``` r
library(tsibble)
#> 
#> Attaching package: 'tsibble'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
library(tsibbledata)
nsw_retail <- aus_retail %>%
  filter(
    State %in% c("New South Wales", "Victoria"),
    Industry == "Department stores"
  )

new_data(nsw_retail)
#> # A tsibble: 2 x 3 [1M]
#> # Key:       State, Industry [2]
#>   State           Industry             Month
#>   <chr>           <chr>                <mth>
#> 1 New South Wales Department stores 2018 Oct
#> 2 Victoria        Department stores 2018 Oct

new_data(nsw_retail) %>% 
  nest(-State) %>% 
  unnest(key = id(State, Industry))
#> # A tsibble: 2 x 3 [?]
#> # Key:       Industry, State [2]
#>   State           Industry             Month
#>   <chr>           <chr>                <mth>
#> 1 New South Wales Department stores 2018 Oct
#> 2 Victoria        Department stores 2018 Oct
```

<sup>Created on 2019-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by earowang** [comment]
Actually I have just changed this behaviour for all tidyr reshaping verbs last night to recalculate the interval https://github.com/tidyverts/tsibble/tree/950b4f4c4d82d82285d61f0ea0bbee739200537e, which I believe is more appropriate.

Furthermore, `nest()` essentially calls `[.tbl_ts`---row subsetting always triggers interval recalculation. For fable, the argument `new_data` in `forecast()` should rely on the pre-specified interval.

**Comment by mitchelloharawild** [comment]
In that case, how do you set the interval when unnesting? Suppose you know the data is monthly in the above example, and you want the interval to reflect that.

**Comment by earowang** [comment]
Users might know, but the function doesn't know by any means. When `nest()`ing, the interval has already been changed. To specify the desired interval, one needs to use low-level constructor `build_tsibble()`.

But `forecast()` would be expected to behave like `new_data()`: inheriting the interval from the data input.

**Comment by mitchelloharawild** [comment]
Yes - that's what I'm saying.
If the users know what the correct interval is, but `tsibble` does not. There should be a user-friendly way to override the interval computed by tsibble (perhaps with optional validation).

`build_tsibble()` is not a user friendly function for specifying a custom interval. Perhaps `update_tsibble()` can have an interval argument.

**Comment by earowang** [comment]
I'm closing this issue. But feel free to open a new ticket on `update_tsibble()`.
