### ISSUE TITLE
Add support for overriding computed interval with update_tsibble()

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/tsibble#104]
Related: #103 

Users may be smarter than tsibble's `pull_interval()` functionality, and should be able to change the interval. This new interval should be checked (when `validate = TRUE`).

**Comment by earowang** [comment]
it doesn't feel compelling to me, esp exposing a key argument purely determined by algorithm for an edge case. No good mechanism to resolve the potential conflicts between user's interval and tsibble's interval yet.

**Comment by mitchelloharawild** [comment]
Fine for now. I suspect that this may come up again in the future, once user intervals become more of a consideration.
