### ISSUE TITLE
Custom yearquarter() character parser

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/tsibble#107]
As `anytime` cannot parse `"2004 Q2"` or `"Q2 2004"`, can we add a simple parser for these formats? If the input format does not match this, it could fall back to anytime.

cc @robjhyndman

**Comment by mitchelloharawild** [comment]
Here is a regular expression that can be used: `\d{4} *Q\d|Q\d *\d{4}`

**Comment by earowang** [comment]
Can you do a PR then?

**Comment by mitchelloharawild** [comment]
Sure.

**Comment by earowang** [comment]
can you make sure it captures “Q”, Qtr, Quarter, and lowercase q as well?

**Comment by earowang** [comment]
also it doesn’t need 4 digits, can be 2 digits for year.

**Comment by mitchelloharawild** [comment]
Making this simple request more complicated.. fine.

**Comment by mitchelloharawild** [comment]
What's your year threshold for parsing 2 digit years?

**Comment by earowang** [comment]
Right. Please abort if the number of digits < 4
