### ISSUE TITLE
`tile_dbl` does not work with mutate when .size>1

### ISSUE THREAD

**Issue by kvasilopoulos** [tidyverts/tsibble#110]
The error below indicates that the new column is the 1/.size of the initial column. 
Probably you will have to pad with NA in order for it to work with `mutate`.

``` r
library(tsibble)

ggplot2::economics %>%
  as_tsibble(index = date) %>%
  mutate(temp = tile_dbl(pce, mean, .size = 1))
#> # A tsibble: 574 x 7 [1D]
#>    date         pce    pop psavert uempmed unemploy  temp
#>    <date>     <dbl>  <int>   <dbl>   <dbl>    <int> <dbl>
#>  1 1967-07-01  507. 198712    12.5     4.5     2944  507.
#>  2 1967-08-01  510. 198911    12.5     4.7     2945  510.
#>  3 1967-09-01  516. 199113    11.7     4.6     2958  516.
#>  4 1967-10-01  513. 199311    12.5     4.9     3143  513.
#>  5 1967-11-01  518. 199498    12.5     4.7     3066  518.
#>  6 1967-12-01  526. 199657    12.1     4.8     3018  526.
#>  7 1968-01-01  532. 199808    11.7     5.1     2878  532.
#>  8 1968-02-01  534. 199920    12.2     4.5     3001  534.
#>  9 1968-03-01  545. 200056    11.6     4.1     2877  545.
#> 10 1968-04-01  545. 200208    12.2     4.6     2709  545.
#> # ... with 564 more rows

ggplot2::economics %>%
  as_tsibble(index = date) %>%
  mutate(temp = tile_dbl(pce, mean, .size = 5))
#> Error: Column `temp` must be length 574 (the number of rows) or one, not 115

ggplot2::economics %>%
  as_tsibble(index = date) %>%
  dplyr::pull(pce) %>%
  tile_dbl(mean, .size = 5) %>%
  head(5)
#> [1] 513.04 536.20 561.48 580.12 598.14
```

**Comment by earowang** [comment]
Unlike `slide()` & `stretch()`, `tile()` is expected to return a single value for each window, working with `summarise()` instead of `mutate()`.

**Comment by kvasilopoulos** [comment]
tbls with no groups will result in one row, but I guess this is where the `index` comes in. So `index`, in this case, works as `group_by`. 

However, providing `tile` through `summarise` and into a vector give different output. Is this intended?

``` r
library(tsibble)

x1 <- 
  ggplot2::economics %>%
  as_tsibble(index = date) %>% 
  summarise(temp = tile_dbl(pce, mean, .step = 5)) %>% 
  dplyr::pull(temp)

length(x1)
#> [1] 574

x2 <- 
  ggplot2::economics %>%
  as_tsibble(index = date) %>%
  dplyr::pull(pce) %>%
  tile_dbl(mean, .size = 5)  

length(x2)
#> [1] 115
```

**Comment by earowang** [comment]
`summarise()` a tsibble gives the summaries over time, and hence `x1` returns itself regardless of `tile()`.

Why do you want `tile()` to return the output of the same length as the input? `slide()` and `stretch()` are made length-stable because their results could be varied in lengths, but `tile()` always results in a reduced form of one value.

**Comment by kvasilopoulos** [comment]
I completely agree with you. My initial remark was the `tile()` does not work with `mutate()` due to length reduction and you proposed that I should use it with `summarize()` instead, but as you said `summarize()` returns the series itself. What I said, in the beginning, is whether you considered when working with `tbl` to pad with NA to make it work with mutate ( even as an argument such as `pad = TRUE`)?

I guess it could work in the same way as `stretch_dbl()`  when you specify  `.step >1"

``` r
library(tsibble)

ggplot2::economics %>% 
  as_tsibble() %>% 
  mutate(mtile = stretch_dbl(pce, mean, .step = 4)) 
#> Using `date` as index variable.
#> # A tsibble: 574 x 7 [1D]
#>    date         pce    pop psavert uempmed unemploy mtile
#>    <date>     <dbl>  <int>   <dbl>   <dbl>    <int> <dbl>
#>  1 1967-07-01  507. 198712    12.5     4.5     2944  507.
#>  2 1967-08-01  510. 198911    12.5     4.7     2945   NA 
#>  3 1967-09-01  516. 199113    11.7     4.6     2958   NA 
#>  4 1967-10-01  513. 199311    12.5     4.9     3143   NA 
#>  5 1967-11-01  518. 199498    12.5     4.7     3066  513.
#>  6 1967-12-01  526. 199657    12.1     4.8     3018   NA 
#>  7 1968-01-01  532. 199808    11.7     5.1     2878   NA 
#>  8 1968-02-01  534. 199920    12.2     4.5     3001   NA 
#>  9 1968-03-01  545. 200056    11.6     4.1     2877  522.
#> 10 1968-04-01  545. 200208    12.2     4.6     2709   NA 
#> # ... with 564 more rows
```

**Comment by earowang** [comment]
I think `tile()` isn't compatible with `mutate()`. So I didn't implement that way. What's the use case that `tile()` is useful for padding with `NA`?

**Comment by kvasilopoulos** [comment]
Fair enough.  I don't have an example in mind, however, in terms of conformity I believe that these 3 window function should behave similarly, that's why I made the suggestion to pad with `NA`. 

A use I can think of, although not very realistic, is the use of `tile()` for averaging variables in non-standard time intervals, such as `3-quarters`, `5-weeks`, `2-years` ,`15-days` etc. Thus it would be easier to work in a tbl with an `index` column rather than working with vectors. 

Anyway, you made your point. You can close now if you want.
