### ISSUE TITLE
Improve error message for grouping by index.

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/tsibble#117]
Many students are getting confused by the error message below.

Could this be improved by also mentioning that tsibble implicitly groups by the time index? This could also be a good opportunity to point users toward the `index_by()` function.

Perhaps something like this would be better:
> Column `Quarter` (index) cannot be a grouping variable. A tsibble is always grouped by its index, if you want to group by a new index consider the `index_by()` function.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tsibble)
#> 
#> Attaching package: 'tsibble'
#> The following object is masked from 'package:dplyr':
#> 
#>     id
tourism %>% 
  group_by(Quarter)
#> Column `Quarter` (index) can't be a grouping variable.
```

<sup>Created on 2019-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by earowang** [comment]
What operation do they usually do following `group_by()`?

**Comment by mitchelloharawild** [comment]
I haven't noticed any difference in subsequent use of operations from regular tibbles. That is to say, most people would use `group_by()` and `summarise()`.
