### ISSUE TITLE
dev tidyr will need new unnest method

### ISSUE THREAD

**Issue by hadley** [tidyverts/tsibble#121]
Just a heads up to let you know that you'll need a new unnest method for dev tidyr since the interface has changed a bit.

**Comment by earowang** [comment]
Thanks. Have added `unnest_tsibble()` as a workaround.

btw, `unnest()` in the **tidyr** dev has some performance issue, much slower than the previous version.

**Comment by hadley** [comment]
That's because it uses vctrs, which will be much faster before release
