### ISSUE TITLE
conversion to ts fails for single observation tsibble

### ISSUE THREAD

**Issue by bdemeshev** [tidyverts/tsibble#124]
I need to make 1-step ahead forecasts with predictors. For this goal I filter one row from the tsibble with all observations and convert it to ts. The conversion fails. So I transform tsibble to tibble, deselect date and than convert to ts. Is there a better way?

``` r
library(tsibble)
one_obs = tsibble(date = as.Date("2017-01-01"), gdp = 5)
#> Using `date` as index variable.
one_obs %>% as.ts()
#> Error in if (frequency > 1 && abs(frequency - round(frequency)) < ts.eps) frequency <- round(frequency): missing value where TRUE/FALSE needed
one_obs %>% as_tibble() %>% dplyr::select(-date) %>% as.ts()
#> Time Series:
#> Start = 1 
#> End = 1 
#> Frequency = 1 
#>      gdp
#> [1,]   5
```

**Comment by earowang** [comment]
Looks like a bug. Your approach looks good. I can't think about a better way. But you may also want to give `tsbox` a try.
