### ISSUE TITLE
support durations in slide(), tile(), strech()

### ISSUE THREAD

**Issue by mkoohafkan** [tidyverts/tsibble#130]
It is common to apply moving-window averages to a time series, e.g. 3-day moving average, 7-day moving average, etc. Currently, `slide()` and `tile()` require that the window size is specified in terms of the number of observations. It would be neat if these functions could also support a duration (e.g. the `lubridate::duration` class) as an alternative way to specify the window size.

On a related note, it would be helpful to have some helper functions for converting the `tsibble::interval` class to a `difftime` object `lubridate::duration` class (the `lubridate::interval` class represents something different from the `tsibble::interval` concept), e.g.
```r
as.duration.interval = function(x) {
  lubridate::as.duration(format(x))
}
interval(some_tsibble)
## 1D
as.duration(interval(some_tsibble))
## "86400s (~1 days)"
```
For a regular tsibble, the window size can then be computed with
```r
lubridate::duration("3 days") / as.duration(interval(d))
```

**Comment by earowang** [comment]
It would be a nice feature to have for rolling window operations. But this set of functions are designed for general purposes; that is, the input data is of arbitrary type, ranging from numeric vectors to data frames. The example below shows that `slide_dbl()` takes a numeric vector `temp` instead of a whole tsibble data. In this case, `slide()` has no way to infer temporal information from index, because the input isn't the tsibble object. 

```r
full_weather %>% 
  group_by_key() %>% 
  mutate(temp_ma = slide_dbl(temp, ~ mean(., na.rm = TRUE), .size = 3))
#> # A tsibble: 26,190 x 6 [1h] <America/New_York>
#> # Key:       origin [3]
#> # Groups:    origin [3]
#>   origin time_hour            temp humid precip temp_ma
#>   <chr>  <dttm>              <dbl> <dbl>  <dbl>   <dbl>
#> 1 EWR    2013-01-01 01:00:00  39.0  59.4      0    NA  
#> 2 EWR    2013-01-01 02:00:00  39.0  61.6      0    NA  
#> 3 EWR    2013-01-01 03:00:00  39.0  64.4      0    39.0
#> 4 EWR    2013-01-01 04:00:00  39.9  62.2      0    39.3
#> 5 EWR    2013-01-01 05:00:00  39.0  64.4      0    39.3
#> # … with 2.618e+04 more rows
```

**Comment by mkoohafkan** [comment]
Would it not be possible to infer the interval using `rlang::.data` when used inside a mutate function?

**Comment by earowang** [comment]
yes the scope environment can be detected via  rlang inside mutate(), which
will be my approach for #55. But it’s more of a hack, which would introduce
some confusion outside mutate().

**Comment by earowang** [comment]
Closing this, since the window functions are deprecated in favour of the {slider} package.
