### ISSUE TITLE
any possibility of processing large time series in chunks

### ISSUE THREAD

**Issue by alperyilmaz** [tidyverts/tsibble#132]
Supporting sparklyr (#109 ) would be a nice touch but it would be also very nice if it's possible to analyze large graphs with tsibble even if they don't fit memory by splitting into chunks and do per-chunk operations without setting a Spark cluster.

There's wonderful package [disk.frame](https://github.com/xiaodaigh/disk.frame) which allows data frames to be split into compressed random accessible (fst) chunks and then allows dplyr verbs to be used to process each chunk.

It might be challenging to figure out best way to split time series into chunks but there might be some workarounds or algorithms to do so which might be integrated with tsibble.

**Comment by earowang** [comment]
Assuming data processing here means data wrangling for large collections of time series, I think it is possible to process tsibble in chunks like what **disk.frame** currently does for `data.frame`.  A tsibble IS a `data.frame` attached with some meta data. The challenging part is how to update those meta data when data chunks are manipulated. 

Regarding how to split a tsibble, a natural way is to split by keys. It will keep the temporal order valid for a time series.

**Comment by alperyilmaz** [comment]
Previously I contacted the author about time series [xiaodaigh/disk.frame/#81](https://github.com/xiaodaigh/disk.frame/issues/81#issuecomment-501703589), upon your suggestion I'll ask the author if it's possible to keep order during sharding chunks.

That's the advantage of disk.frame, each chunk is a data.frame and anything possible to calculate for a data.frame is also possible. However, there's map-reduce approach to be taken if an aggregate operation is needed. 
For instance, if a mean of Departure Delay per Carrier (sorry, this is not a time series example) is to be calculated, then there should be two stage group-by to be applied per chunk, and the trick is each chunk does not return average, they return sum and count, the average is calculated at second stage. Here's an example code:

```R
flights_disk_frame %>%
  ##per-chunk
  filter(!is.na(DepDelay)) %>%
  group_by(UniqueCarrier) %>%                              ##MAP
  summarize(count=n(), total_delay=sum(DepDelay)) %>%      ##
  ##per-chunk
  collect %>% 
  group_by(UniqueCarrier) %>%                                         ##
  summarise(TotalFlights=sum(count),TotalDelay=sum(total_delay)) %>%  ##REDUCE
  ungroup()                                                           ## 
  mutate(overall_delay=TotalDelay/TotalFlights)                       ## ACTUAL MEAN CALCULATION
```

I was wondering, provided that the temporal order in chunks kept in index order, if it's possible to use some or most of the functions listed in [tsibble reference](https://tsibble.tidyverts.org/reference/index.html) per chunk and combine results in map-reduce approach?

**Comment by earowang** [comment]
The `mean()` example can be tackled with the map-reduce approach, but operations relying on sorting first probably aren't straightforward, such as `quantile()`. Many tsibble functions have been vectorised, that can be used for chunks. But it depends on what kind of statistics you're interested in computing, not tsibble's functions.

Although tsibble follows tabular data structure, tsibble currently cannot use the operations from **disk.frame** for free. It would require a new tsibble-like data class on top of `disk.frame`, similarly `tsibble` on top of `tibble`. And dplyr generics will be extended to support this new class. It would involve lots of implementation. (The implementation load may be reduced, if both packages are migrated into the **vctrs** framework, which also takes time)

**Comment by earowang** [comment]
Closed for now. Out of the package scope.
