### ISSUE TITLE
`yearmonth()` does not support character formats like `2019 M01`

### ISSUE THREAD

**Issue by zenggyu** [tidyverts/tsibble#142]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Is there a reason why `yearweek()` does not work with `2019 W01` like `yearquarter()` with `2019 Q1`?

```r
library(tsibble)
yearweek("2019 W1")
#> Error: Input data '2019 W1' cannot be expressed as Date type
yearquarter("2019 Q1")
#> [1] "2019 Q1"
```

Currently `yearweek()` works with formats like `2019 01`, but this can be confusing because `01` is interpreted as month instead of week. It would be more consistent and less confusing if `yearweek()` supports a format like `2019 W01`.

`yearmonth()` has a similar problem because it does not work with `2019 M01`. Although it is not necessary but I think this will help increase consistency.

**Comment by earowang** [comment]
Can you update tsibble to the latest CRAN release for the new feature of `yearweek()`?

**Comment by zenggyu** [comment]
OK, `yearweek()` works as expected now.

**Comment by zenggyu** [comment]
Here's a related issue. The printing results of `yearmonth()` are inconsistent among different locales, e.g., 

```r
library(tsibble)
Sys.setlocale(locale = "en_US.utf8")
#> [1] "LC_CTYPE=en_US.utf8;LC_NUMERIC=C;LC_TIME=en_US.utf8;LC_COLLATE=en_US.utf8;LC_MONETARY=en_US.utf8;LC_MESSAGES=zh_CN.UTF-8;LC_PAPER=zh_CN.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=zh_CN.UTF-8;LC_IDENTIFICATION=C"
yearmonth("2019 01")
#> [1] "2019 Jan"
Sys.setlocale(locale = "zh_CN.utf8")
#> [1] "LC_CTYPE=zh_CN.utf8;LC_NUMERIC=C;LC_TIME=zh_CN.utf8;LC_COLLATE=zh_CN.utf8;LC_MONETARY=zh_CN.utf8;LC_MESSAGES=zh_CN.UTF-8;LC_PAPER=zh_CN.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=zh_CN.UTF-8;LC_IDENTIFICATION=C"
yearmonth("2019 01")
#> [1] "2019 1月"
```

This can cause problems when running scripts on different machines. Perhaps `yearmonth()` should not only accept a format like `2019 M01`, but also display the value in this format to achieve consistency.

**Comment by earowang** [comment]
The underlying values are the same. Display formats should depend on locale.

**Comment by earowang** [comment]
If you're concerned about the *displays* across machines, this is the solution

``` r
Sys.setlocale(locale = "zh_CN.UTF-8")
#> [1] "zh_CN.UTF-8/zh_CN.UTF-8/zh_CN.UTF-8/C/zh_CN.UTF-8/en_AU.UTF-8"
print(tsibble::yearmonth("2019 01"), format = "%Y M%m")
#> [1] "2019 M01"
```

<sup>Created on 2019-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by zenggyu** [comment]
Ah, good to know about that, thanks!

**Comment by ghost** [comment]
My issue is similar to this one.  yearmonth() doesn't work with `January 1972`, but does work with `1972 January`.

``` r
library(tsibble)
yearmonth("January 1972")
#> Error: Input data 'January 1972' cannot be expressed as Date type
yearmonth("1972 January")
#> [1] "1972 Jan"
```

Is this expected behavior?

**Comment by zenggyu** [comment]
Another issue: why does `yearmonth('201811')` return `"2018 Jan"`, and `yearmonth(201811)` return `"201674 Nov"`? I think in both cases the function should return `"2018 Nov"`, or perhaps throw an error indicating that `yeamonth()` does not support those formats. I just spent quite some time on a bug caused by this behaviour.

**Comment by davidtedfordholt** [comment]
@earowang , I think the last little bit of this is allowing the `January 2018` format. @eddelbuettel pointed out that the format can easily be added before the calls to `anytime::assertDate()` and `anytime::anydate()` with `addFormats("%B %Y")`. Running that line takes too little time for my system to record it, so I'm inclined to add it there, but it could also go in the `.onLoad()`.

**Comment by earowang** [comment]
Thanks @davidtedfordholt . Would you be okay to send a new PR just using {anytime} to handle the issue?

``` r
library(anytime)
addFormats(c("%B %Y", "%b %Y", "%Y M%m", "%Y m%m"))
anydate(c("January 2018", "Jan 2018", "2018 M01", "2018 m1"))
#> [1] "2018-01-01" "2018-01-01" "2018-01-01" "2018-01-01"
```

<sup>Created on 2020-09-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by davidtedfordholt** [comment]
I am already testing one!
