### ISSUE TITLE
`[.year*` performance is slow

### ISSUE THREAD

**Issue by MilesMcBain** [tidyverts/tsibble#146]
I'm seeing some strange performance behaviour calling `dplyr` joins on large tsibbles with lots of keys (4.2M rows, 45K keys). 

For example this code, ran for over 30 minutes without returning:
 
```
incident_time_series2 %>%
  rename(h3Index = H3Index) %>%
  mutate(year = as.integer(year(!!tsibble::index(incident_time_series2)))) %>%
  left_join(
    hex_pop_long2,
    by = c("h3Index", "year")
  )
```
while almost identical code that joins after coercion to `tibble` returns almost instantly:

```
incident_time_series2 %>%
rename(h3Index = H3Index) %>%
mutate(year = as.integer(year(!!tsibble::index(incident_time_series2)))) %>%
as_tibble() %>%
  left_join(
    hex_pop_long2,
    by = c("h3Index", "year")
  )
```
When I profile the long running version with `profvis`, I see repeated calls to `tsibble::yearmonth`, that seem to be triggering an unusual amount of garbage collection. Profiler output of  it running for about a minute before interruption is attached.
[profvis.zip](https://github.com/tidyverts/tsibble/files/3588729/profvis.zip)

I've got the two datasets I used in the code hosted on my Google drive, ready to share with you if you need them. I'd prefer to share privately rather than over open internet, given the size. So I'll email them to you if let me know.

**Comment by earowang** [comment]
Thanks Miles. Yes, tsibble's `year*()` functions seem to be slow, also affecting the forecasting speed. I hope to tackle the performance issue when I re-write them using vctrs.

Is `index(incident_time_series2)` a `yearmonth` object?

**Comment by MilesMcBain** [comment]
Yep its a `yearmonth` object.

**Comment by earowang** [comment]
Also `left_join()` tsibble with a non-tsibble triggers the check if the output is a valid tsibble, which takes longer than joining data frames.

**Comment by MilesMcBain** [comment]
Ah okay. Yes it seems to be the validation which is spooling for a long time.

```
  tsibble:::retain_tsibble(incident_time_series2,
                           tsibble::key(incident_time_series2),
                           tsibble::index(incident_time_series2)
                           )
```

Above not returning for me. 

Looking at the profiler, this summarise looks like the last sensible code before things go a bit wild:
https://github.com/tidyverts/tsibble/blob/b7b93395b595d6aad3ef87478850a8b8f624b151/R/as-tsibble.R#L545

**Comment by earowang** [comment]
Are you using the dev version of  tsibble? The `[.yearmonth` looks like to be called recursively in the profvis result.

**Comment by MilesMcBain** [comment]
No sorry I'm on CRAN version. I'll try dev now.

**Comment by MilesMcBain** [comment]
The profiler output looks the same on master.

**Comment by earowang** [comment]
Adding a reprex to the issue. It is the `[.yearmonth` issue, not `vctrs::vec_duplicate_any()`.

```r
library(tsibble)
key <- rep(1:45000, each = 10)
index <- rep(yearmonth("2010 Jan") + 0:9, times = 45000)
tsbl <- tibble(key = key, index = index)
is_duplicated(tsbl, key = key, index = index)
```

The vctrs support will start in two or three weeks.

``` r
library(tsibble)
library(vctrs)
library(dplyr, warn.conflicts = FALSE)
yrmth <- yearmonth("2010 Jan") + 0:99
date <- as.Date("2010-01-01") + 0:99
bench::mark(
  yearmonth = yrmth[1:100],
  date = date[1:100],
  check = FALSE
)
#> # A tibble: 2 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 yearmonth   15.09µs  17.04µs    55471.    9.48KB     22.2
#> 2 date         4.67µs   5.57µs   165577.    1.27KB     16.6
tbl <- 
  tibble(
    grp = rep(letters[1:10], 10), yrmth = yrmth,
    date = date
  ) %>% 
  group_by(grp)
bench::mark(
  yearmonth = summarise(tbl, vec_duplicate_any(yrmth)),
  date = summarise(tbl, vec_duplicate_any(date)),
  check = FALSE
)
#> # A tibble: 2 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 yearmonth     709µs    781µs     1235.  119.66KB     15.1
#> 2 date          340µs    363µs     2693.    1.92KB     12.5
```

<sup>Created on 2019-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MilesMcBain** [comment]
Thanks Earo! 😅

**Comment by earowang** [comment]
Migrating to the vctrs framework fixes the recursive function call issue.

``` r
library(tsibble)
key <- rep(1:45000, each = 10)
index <- rep(yearmonth("2010 Jan") + 0:9, times = 45000)
tsbl <- tibble(key = key, index = index)
is_duplicated(tsbl, key = key, index = index)
#> [1] FALSE
```

<sup>Created on 2019-11-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
