### ISSUE TITLE
forecast::monthdays equivalent

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/tsibble#148]
It is sometimes useful to adjust monthly data by the number of days in the month (to give sales per day for example). In the forecast package, the number of days per month is easily computed using `monthdays()`. It would be useful to have something similar in the tsibble world, but perhaps more general so it works for annual and quarterly data as well. Perhaps `number_days()`.

**Comment by earowang** [comment]
Is `lubridate::days_in_month()` the function you're looking for?

``` r
library(tsibble)
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:tsibble':
#> 
#>     interval, new_interval
#> The following object is masked from 'package:base':
#> 
#>     date
days_in_month(as_date(yearmonth("2019 Jan") + 0:8))
#> Jan Feb Mar Apr May Jun Jul Aug Sep 
#>  31  28  31  30  31  30  31  31  30
```

<sup>Created on 2019-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by robjhyndman** [comment]
Ah yes. Thanks.
