### ISSUE TITLE
ggplot::scale_year*()

### ISSUE THREAD

**Issue by earowang** [tidyverts/tsibble#149]
I've migrated `year*` classes to the **vctrs** framework. They are no longer a subclass of date, which means `ggplot2::scale_x_date()` isn't compatible anymore and they need their own scales functions. Can you @mitchelloharawild update `scale_year*` and contribute to the dev branch https://github.com/tidyverts/tsibble/tree/dev-v0.9.0 ?

**Comment by mitchelloharawild** [comment]
I'm currently running into an issue where `labeling::extended` cannot be ran because the `year*` classes do not support operations on themselves (in particular, a-b). Is this something you're planning to support, or should adding scales also involve writing custom plot break functions?

**Comment by earowang** [comment]
Added the `-` support.

**Comment by earowang** [comment]
`scale_yearmonth` works but not `scale_yearquarter` and `scale_yearweek`. Not exactly sure why ggplot2's ranges return some strange values.

**Comment by mitchelloharawild** [comment]
Thanks, I'll look into this.

**Comment by mitchelloharawild** [comment]
Seems to not work on CRAN ggplot2, but works on dev ggplot2 (which is what I tested against).
Not sure why this is the case, could take a little while to fix.

**Comment by earowang** [comment]
Any luck on this? I could push the v0.9.0 release later, and get v0.8.4 out for the cran fix.

**Comment by mitchelloharawild** [comment]
Haven't had the chance to look into it, It would be nice if you could push the v0.8.4 CRAN fix first.

From what I could see in the revdep, there will be a bit of work involved in updating fabletools for the`v0.9.0` tsibble changes.

**Comment by earowang** [comment]
Okay, good to know.
