### ISSUE TITLE
are_duplicated() Error: std::bad_alloc due to keys being factors with many levels.

### ISSUE THREAD

**Issue by JustGitting** [tidyverts/tsibble#157]
Hi,

I discovered this error when my GNU/Linux machine locked up due the way the kernel over allocates memory to processes and does not handle the clearing/allocating of space effectively. Please see the following references for details.

OOM killer doesn't work properly, leads to a frozen OS
[https://unix.stackexchange.com/questions/373312/oom-killer-doesnt-work-properly-leads-to-a-frozen-os](https://unix.stackexchange.com/questions/373312/oom-killer-doesnt-work-properly-leads-to-a-frozen-os)

limiting memory usage in R under linux
[https://stackoverflow.com/questions/12582793/limiting-memory-usage-in-r-under-linux/24475329
](https://stackoverflow.com/questions/12582793/limiting-memory-usage-in-r-under-linux/24475329)

I was able to isolate the cause of my problem to R and specifically the are_duplicate() function.

In short, the problem occurs when multiple keys that are factors with a large number of levels are used. Depending on the number of levels, the error is either **memory exhausted** or **std::bad_alloc**.

The problem does not occur when there is only one key is a factor.

R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
tsibble: 0.8.5
64GB of RAM

Below is a reproducible example for both cases (memory exhausted and bad_alloc).

**WARNING**
DO NOT execute the following examples on a GNU/Linux system without setting the overcommit_memory setting to 2 (only allocate what is physically available). Otherwise it will likely freeze your system.

As root, run:
` # echo 2 > /proc/sys/vm/overcommit_memory
`
Once you are finished debugging, please revert overcommit_memory to zero (0).

```
n <- 10000
fruit_with_n_factors <- tibble(
  date = (as.Date('2001-01-01') + seq(n) ),
  fruit = as.factor( seq(n) ),
  kilo = as.factor( seq(n)) )

are_duplicated(fruit_with_n_factors, key = c(fruit, kilo), index = date)

Error: memory exhausted (limit reached?)

```

```
n <- 100000
fruit_with_n_factors <- tibble(
  date = (as.Date('2001-01-01') + seq(n) ),
  fruit = as.factor( seq(n) ),
  kilo = as.factor( seq(n)) )

are_duplicated(fruit_with_n_factors, key = c(fruit, kilo), index = date)

Error: std::bad_alloc 
```

Checking the traceback() yields:

```
> traceback()
5: stop(list(message = "std::bad_alloc", call = NULL, cppstack = NULL))
4: grouped_df_impl(data, unname(vars), drop)
3: grouped_df(data, vars = key)
2: mutate(grouped_df(data, vars = key), `:=`(!!"zzz", duplicated.default(!!index,
                                                                         fromLast = from_last)))
1: tsibble::are_duplicated(ed_data %>% filter(!is.na(date)),
                           key = c(fruit, kilo), index = date)
```

With n <= 5000 the is no memory related error, but it does slow down. I have not done exhaustive tests on the exact size of n that produces the above detailed error.

The workaround to this problem is to convert the keys that are factors to their native format, i.e. numeric or characters types.

I'm not sure if this is expected or not. Let me know if you need further information.

**Comment by earowang** [comment]
In the example you gave, isn't the key just `fruit`? If so, the example runs fine on my local machine.

```r
are_duplicated(fruit_with_n_factors, key = fruit, index = date)
```

As the `traceback()` suggested, it roots in `dplyr::grouped_df()`. What's your dplyr version?

**Comment by JustGitting** [comment]
Hi,

mmm, no, I'm not using a single key, I'm using a compound key of fruit and kilo in the above examples:

```
are_duplicated(fruit_with_n_factors, key = c(fruit, kilo), index = date)
```

The version of dplyr is: 0.8.3

**Comment by earowang** [comment]
Okay, I traced down the problem. Will fix in the next release. Thanks.

**Comment by JustGitting** [comment]
Thank you Earo.
