### ISSUE TITLE
Incompatibility with Prophet

### ISSUE THREAD

**Issue by ranalytics** [tidyverts/tsibble#163]
**What I am trying to do**

I am fitting a forecasting model using the [Prophet package](https://github.com/facebook/prophet) to a `tsibble` that contains a single time series with observations recorded daily.

**What the problem is**

The model fitting part goes well, but when I am trying to plot the resulting forecast, I am getting this error:
`Error: Can't obtain the interval due to the mismatched index class.  
Please see ``vignette("FAQ")`` for details.`

Indeed, the error is documented in the FAQ vignette and is seemingly related to how the time interval is specified. However, as can be seen in the reprex below, the date column is specified correctly, and the aforementioned problem thus seems to be some sort of a bug that leads to incompatibility between the Prophet's plotting function and `tsibble`. And it seems to be a `tsibble` problem - when the data class is changed to `tibble`, everything works just fine.

**Minimal reproducible example**

```r
require(tsibble)
require(dplyr)
require(lubridate)
require(prophet)
require(nycflights13)


# Data prep:
weather <- nycflights13::weather %>% 
  filter(origin == "EWR") %>% 
  select(time_hour, temp) %>% 
  as_tsibble(key = NULL, index = time_hour)

weather

temp_high <- weather %>%
  index_by(ds = as_date(time_hour)) %>% 
  summarise(y = max(temp, na.rm = TRUE))

temp_high

has_gaps(temp_high)
is_regular(temp_high)


# Model fitting (goes without issues):
m1 <- prophet(temp_high)

# Calculating the forecast (goes without issues):
future_df_m1 <- make_future_dataframe(m1, periods = 20)
forecast_m1 <- predict(m1, future_df_m1)
forecast_m1[, c("yhat", "yhat_lower", "yhat_upper")] %>% head()

# Trying to plot the forecast - this part fails:
plot(m1, forecast_m1)


# The same forecasting exercise, but on a tibble instead of tsibble - all fine:
m2 <- temp_high %>% 
  as_tibble() %>% 
  prophet(.)

future_df_m2 <- make_future_dataframe(m2, periods = 10)
forecast_m2 <- predict(m2, future_df_m2)
forecast_m2[, c("yhat", "yhat_lower", "yhat_upper")] %>% head()

plot(m2, forecast_m2)
```

**Comment by mitchelloharawild** [comment]
The prophet package expects a `data.frame` input, not a tsibble.
To make this work, changes should be made to the [prophet package](https://github.com/facebook/prophet/) to coerce inputted data to a data.frame before usage.

To use a prophet model with tsibble, I'd recommend looking into the [fable.prophet](https://github.com/mitchelloharawild/fable.prophet/) package, which makes the prophet model usable in a [fable](https://fable.tidyverts.org/) workflow.

**Comment by ranalytics** [comment]
Thank you for your reply, @mitchelloharawild. I totally understand that it's pretty much impossible to foresee what other packages would be using `tsibble`-based datasets, and thus impossible to achieve 100% compatibility. It's rather weird though, in this specific example, that the `prophet` package happily accepts a `tsibble` and actually builds the model it's expected to build, but then fails when it comes to plotting. But I guess it's a question to be addressed to the `prophet` authors...

As for the `tsibble` package, from the user experience perspective I believe it's rather confusing to see an error massage that says the problem is with how the data interval is specified because in the example given above the interval (`[1D]`) is specified correctly. So maybe there is still something in `tsibble` that needs to be looked at? If I am mistaken here, this issue can be closed.

**Comment by mitchelloharawild** [comment]
The error is due to the following:

1. The prophet package converts the ds column to a `POSIXt`, but retains the tsibble structure
1. tsibble is strict on using minimal datetime classes as the index, and as POSIXt (a date and time class) is used for data without a time element, it errors (see discussion in #145). I believe this is done for correctly handling (or not handling in this case) daylight savings in time zones for computing the interval.

I think if anything, tsibble should error earlier. `data$index <- as.POSIXct(data$index)` allows you to create a tsibble that mismatches the index and the interval.

The prophet package should strip input data down to their expected `data.frame` structure, or use the input data's index class.

**Comment by mitchelloharawild** [comment]
Thanks for letting us know of the issue.

@earowang - do you think more tsibble validation is needed for `$<-`?
