### ISSUE TITLE
different behaviours for summarise() tsibble and tibble

### ISSUE THREAD

**Issue by qiushiyan** [tidyverts/tsibble#166]
I have noticed that `tsibble` objects behaves differently in terms of grouping variables when using dplyr functions. Specifically, it did not automatically use `index` as the grouping variable when I 'm using `mutate()` or `filter()`, while `tsibble` is automatically grouped by `index` in the case of `summarize()` or `count()`. I havn't tried all functions exhaustively, but here is an example.: 

``` r
library(tidyverse)
library(tsibble)
x <- tsibble(Year = 2015:2019, Observation = c(123, 39, 78, 52, 110), 
             index = Year)
# grouped by year
x %>% summarize(mean(Observation))  
#> # A tsibble: 5 x 2 [1Y]
#>    Year `mean(Observation)`
#>   <int>               <dbl>
#> 1  2015                 123
#> 2  2016                  39
#> 3  2017                  78
#> 4  2018                  52
#> 5  2019                 110

x %>% count(Observation)
#> # A tsibble: 5 x 3 [1Y]
#> # Key:       Observation [5]
#>   Observation  Year     n
#>         <dbl> <int> <int>
#> 1          39  2016     1
#> 2          52  2018     1
#> 3          78  2017     1
#> 4         110  2019     1
#> 5         123  2015     1

# not grouped by Year
x %>% filter(min_rank(Observation) == 1)
#> # A tsibble: 1 x 2 [1Y]
#>    Year Observation
#>   <int>       <dbl>
#> 1  2016          39

x %>% mutate(cumsum(Observation))
#> # A tsibble: 5 x 3 [1Y]
#>    Year Observation `cumsum(Observation)`
#>   <int>       <dbl>                 <dbl>
#> 1  2015         123                   123
#> 2  2016          39                   162
#> 3  2017          78                   240
#> 4  2018          52                   292
#> 5  2019         110                   402
```

<sup>Created on 2020-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

```

**Comment by earowang** [comment]
This is an intended behaviour for `summarise()`ing a tsibble over time by default. `summarise()` a normal data frame reduces the values to one, which certainly loses temporal information for a tsibble, and hence invalid anymore.

**Comment by qiushiyan** [comment]
Thanks for the response. Yet I still feel it is a better choice to generalize this grouping behaviour to all `dplyr` functions to ensure better consistency. Or is there any way to "ungroup" a `tsibble` by its index? Now I manually convert a `tsibble` to `tibble` to ungroup it.

**Comment by earowang** [comment]
The consistency of verbs is tsibble in and out. Users won't be surprised to get a different object out from a wrangling verb. 

By explicitly converting to a `tibble`, users **know** they don't want temporal context anymore.

If too much confusion for dplyr users, I'll reconsider the behaviour. Would be more natural to do

```r
tsibble %>%
  index_by() %>%
  summarise()
```

for summaring tsibble over time. Hence `summarise(tsibble)` returns a reduced tibble.

@mitchelloharawild do you think students get confused with `summarise()` a tsibble and tibble in the forecasting class?

**Comment by mitchelloharawild** [comment]
I think I misunderstood this when I first read it. As you suggesting that `index_by()` without arguments prepares the tsibble to lose its index and revert to a tibble?

I think students didn't have too much trouble with `summarise()` on a tibble versus a tsibble. Once they realised that `index_by()` was an option, they were able to use it quickly. 
Are there hints for using `index_by()` when `group_by(index)` is used? If not, this may help.

**Comment by earowang** [comment]
I'm suggesting

```r
tsibble %>% summarise() # returns a tibble
```

and if users want tsibble, they do

```r
tsibble %>% index_by(<empty>) %>% summarise()
```

**Comment by mitchelloharawild** [comment]
I would have thought:

```r
tsibble %>% summarise() # returns a tsibble
```

To get a tibble, they create an empty index2
```r
tsibble %>% index_by(<empty>) %>% summarise()
```

**Comment by earowang** [comment]
Looks like students are not confused with the current behaviour. I suppose It will stay as is at this stage.

**Comment by qiushiyan** [comment]
I think what confuse me is not that `summarize() + tsibble / tibble` behaves differently, but that some dplyr verbs do not operate on `tsibble` the same way like `summarize()`. For example, `filter()` and `mutate()` will not consider `index` as  a grouping variable, so that the following code will return one row instead of 5

```
# not grouped by Year
x %>% filter(min_rank(Observation) == 1)
#> # A tsibble: 1 x 2 [1Y]
#>    Year Observation
#>   <int>       <dbl>
#> 1  2016          39
```

**Comment by mitchelloharawild** [comment]
Yes, I agree this behaviour is confusing and needs further thought.

**Comment by earowang** [comment]
Okay, let's go back to the original issue.

1. There's no way to `ungroup()` tsibble's index except for coercing back to a tibble for current `summarise()` behaviour.
2. If grouping index for every dplyr verb, it'd be no longer possible for  `x %>% filter(min_rank(Observation) == 1)` to return a one-row tsibble, unless back to tibble.
3. If not grouping index for `summarise(<tsibble>)` and hence return a tibble without index, what would be a better alternative operation to `summarise()` a tsibble over index?

The current `summarise()` behaviour has irritated me for a while:

1. other summary-like functions, such as `has_gaps()` and `count_gaps()`, returns a tibble. so should `summarise()`?
2. if `summarise(<tsibble>)` gives a tibble back, `summarise(index_by(<tsibble>))` returns a tsibble. It also seems inconsistent to me.

**Comment by Fuco1** [comment]
The one annoying thing is that something like `group_by_key() %>% as_tibble %>% summarize(x = sum(quantity), .groups = "keep")` doesn't work since the coercion to tibble drops the key information where as simply doing `group_by_key() %>% summarize(x = sum(quantity), .groups = "keep")` also groups by index additionally.

The trick I use now is to stick `index_by(1)` after the `group_by_key` and then drop the column.  I really like using `group_by_key` because it allows me to add more keys to the data without changing my code everywhere.  But I also very often need to get a "sum of all X" over the whole history which is a bit unfriendly.  Maybe a verb like `unindex` similar to `ungroup` would suffice.

**Comment by earowang** [comment]
@Fuco1 can you file a new issue to describe what results you'd like to achieve by including some code examples? I think your issue is more related to https://github.com/tidyverts/tsibble/issues/211 .
