### ISSUE TITLE
base::subset doesn't preserve tsibble class

### ISSUE THREAD

**Issue by hongooi73** [tidyverts/tsibble#168]
While `dplyr::filter` works correctly with tsibbles, `base::subset` returns a tibble:

```r
data(ansett, package="tsibbledata")
subset(ansett, Class == "Business")
```
```
# A tibble: 7,407 x 4
       Week Airports Class    Passengers
     <week> <chr>    <chr>         <dbl>
 1 1989 W28 ADL-PER  Business        193
 2 1989 W29 ADL-PER  Business        254
 3 1989 W30 ADL-PER  Business        185
 4 1989 W31 ADL-PER  Business        254
 5 1989 W32 ADL-PER  Business        191
...
```

This is because while tsibble includes a method for `filter`, it doesn't have one for `subset`. I can make a PR for this.

**Comment by earowang** [comment]
Probably not for tsibble to support base operations at this stage.

1. `subset()` has not just `filter()` semantics but `mutate()`, which complicates implementation.
2. Other data.frame operations like `base::transform()` will also be supported.
3. We tend to encourage dplyr verbs to manipulate the tsibble object.

**Comment by earowang** [comment]
I haven't defined the `subset()` method for tsibble, but now it preserves subclass. Not sure what has changed in `subset.data.frame()`.

``` r
library(tsibble)
library(tsibbledata)
subset(ansett, Class == "Business")
#> # A tsibble: 1,758 x 4 [1W]
#> # Key:       Airports, Class [10]
#>        Week Airports Class    Passengers
#>      <week> <chr>    <chr>         <dbl>
#>  1 1989 W28 ADL-PER  Business        193
#>  2 1989 W29 ADL-PER  Business        254
#>  3 1989 W30 ADL-PER  Business        185
#>  4 1989 W31 ADL-PER  Business        254
#>  5 1989 W32 ADL-PER  Business        191
#>  6 1989 W33 ADL-PER  Business        136
#>  7 1989 W34 ADL-PER  Business          0
#>  8 1989 W35 ADL-PER  Business          0
#>  9 1989 W36 ADL-PER  Business          0
#> 10 1989 W37 ADL-PER  Business          0
#> # … with 1,748 more rows
```

<sup>Created on 2020-07-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
