### ISSUE TITLE
No stretch_tsibble function reference in package documentation

### ISSUE THREAD

**Issue by konradsemsch** [tidyverts/tsibble#172]
I was looking into the cross-validation documentation: [link](https://otexts.com/fpp3/tscv.html) and came across the usage of the `stretch_tsibble` function and wanted to check it further in the online package documentation but it's missing from there: [link](https://tsibble.tidyverts.org/reference/index.html).

![image](https://user-images.githubusercontent.com/15321842/76070765-5f307b00-5f95-11ea-9ee6-9675d99c5ad8.png)

Where can I find further info on this? Is this function deprecated?

**Comment by earowang** [comment]
The documentation page can be accessed via https://tsibble.tidyverts.org/reference/stretch_tsibble.html but not on the reference page. You could still find it using the search box. It's been questioned, not yet deprecated.
