### ISSUE TITLE
rbind.tbl_ts fails for named arguments

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/tsibble#175]
Presumably an identical `TRUE` comparison for `interval` within `build_tsibble_meta` fails due to the named input preserved by `map_lgl`.

``` r
library(tsibble)
ped_split <- split(pedestrian, pedestrian$Sensor)
rbind(a = ped_split[[1]], b = ped_split[[2]])
#> Error: Argument `interval` must be class interval, not logical.
```

<sup>Created on 2020-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by earowang** [comment]
now `bind_rows()` works, and I removed `rbind()` methods.

**Comment by mitchelloharawild** [comment]
Any reason to remove `rbind()` and `cbind()` methods? Doing so will cause revdep issues.

**Comment by earowang** [comment]
1. They are just temporary solutions as `bind_rows/cols()` are not 
available before for subclasses.
2. They produce unpredictable results (e.g. matrix), and I have no 
control over it.
3. The forthcoming tsibble release introduces several breaking changes.

Cheers,
Earo
