### ISSUE TITLE
implement `vec_ptype2(<tbl_ts>, <tbl_df>)` etc

### ISSUE THREAD

**Issue by earowang** [tidyverts/tsibble#183]
https://github.com/r-lib/vctrs/commit/d3cedf87373c45afefd54d84808a521d25bec02f

**Comment by anastasiospanagiotelis** [comment]
This is probably related but attempting to install the dev version currently throws the following error:

Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** testing if installed package can be loaded from temporary location
E> Warning: S3 methods ‘vec_ptype2.tbl_ts’, ‘vec_ptype2.tbl_ts.tbl_ts’ were declared in NAMESPACE but not found
E> Error: package or namespace load failed for ‘tsibble’ in namespaceExport(ns, exports):
E>  undefined exports: vec_ptype2.tbl_ts
E> Error: loading failed
E> Execution halted
E> ERROR: loading failed
E> * removing ‘/tmp/RtmpB1crva/Rinst49e57030048d/tsibble’
E>       -----------------------------------
E> ERROR: package installation failed

**Comment by Ari04T** [comment]
Same issue here... Is there a way to install latest version, or is it a work in progress? Thanks!

**Comment by earowang** [comment]
Not there yet, because the upstream package vctrs hasn't addressed the 
issue.

Cheers,
Earo
