### ISSUE TITLE
Extend `new_data()` to accept n<0

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/tsibble#186]
Just an idea, but this would be useful for backcasting and neaten some code for `components()` in fable. Behaviour is to create data with indices before the start of the data, rather than after the end of the data.

**Comment by earowang** [comment]
Perhaps a new function called `past_data()`, haha

(yep, this can be include in `v0.9.0`, scheduled for May 22.

**Comment by mitchelloharawild** [comment]
In that case `new_data()` might be better named `future_data()`?

**Comment by earowang** [comment]
I was joking...

yes, `new_data(n <0)`
