### ISSUE TITLE
stretch_tsibble() error message when series length is 1

### ISSUE THREAD

**Issue by brshallo** [tidyverts/tsibble#188]
In cases where the series length is one, I think the error message on `stretch_tsibble()` could be more clear.  

``` r
library(fable)
library(tidyverse)
library(lubridate)
library(tsibble)

tibble(key = c("a", "b", "b"), index = ymd(20200101, 20200101, 20200102), x = rnorm(3)) %>% 
  as_tsibble(index = index, key = key) %>% 
  slice(1:(n())) %>%
  stretch_tsibble()
#> Error: `.init` must be less than 1.
```

<sup>Created on 2020-05-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by earowang** [comment]
Thanks. I was confused about the error msg, when I first read... 😅
