### ISSUE TITLE
Switch interval to period (from lubridate)

### ISSUE THREAD

**Issue by earowang** [tidyverts/tsibble#19]
Internally, **tsibble** uses a self-defined class to store the interval. To allow for maths operations on dates, `lubridate::period()` is a better alternative. Thanks @mitchelloharawild for this neat idea.

**Comment by earowang** [comment]
@mitchelloharawild 

`period()` seem not suited to the interval attributes. It doesn't have the "quarter" and "week" slots. If the index is just a sequence of numbers, the interval uses "unit" whereas `period()` doesn't have.

**Comment by mitchelloharawild** [comment]
Could you not use `quarter = 3 months` and `week = 7 days`?
Not sure how to support `unit`, but nonetheless it may be worth looking into how `lubridate::period()` is implemented for a similar implementation within tsibble.

**Comment by earowang** [comment]
```r
tourism
#> # A tsibble: 23,408 x 5 [1QUARTER] or [3MONTH]?
#> # Keys:      Region | State, Purpose [308]
#>   Quarter Region   State           Purpose  Trips
#>     <qtr> <chr>    <chr>           <chr>    <dbl>
#> 1 1998 Q1 Adelaide South Australia Business  135.
#> 2 1998 Q2 Adelaide South Australia Business  110.
#> 3 1998 Q3 Adelaide South Australia Business  166.
#> 4 1998 Q4 Adelaide South Australia Business  127.
#> 5 1999 Q1 Adelaide South Australia Business  137.
#> # ... with 2.34e+04 more rows
```

**Comment by mitchelloharawild** [comment]
`[1QUARTER]` is better for display purposes, but the `period()` object can be `months(3)` for implementation purposes.

**Comment by earowang** [comment]
It's not about printing. `yearmonth()` generates "MONTH" and`yearquarter()` generates "QUARTER". "3MONTH" could be different from the meaning of "1QUARTER".

**Comment by earowang** [comment]
The current "interval" class cannot be fully replaced by "Period". But will implement `as_period()` to convert "interval" to "Period", and maths operations can be carried out then.

**Comment by earowang** [comment]
I'm going to close this issue, bc "Period" is not entirely equivalent to "interval". If the index is "yearmonth", which happens to be 3 months interval, it will generating confusing interpretation (3 month? or 1 quarter?)

**Comment by Fuco1** [comment]
Regarding your previous comment, I understood that should make this work:

```
yearmonth('2020-10-01') + months(1)
Error: Incompatible classes: <yearmonth> + <Period>
```

What am I doing wrong?  I'm currently doing this:

    yearmonth(as.Date(yearmonth('2020-10-01')) + months(1))

which is a bit silly :)

**Comment by earowang** [comment]
An easier way to do this would be just plus a number?
``` r
library(tsibble)
#> 
#> Attaching package: 'tsibble'
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, union
yearmonth('2020-10-01') + 1
#> <yearmonth[1]>
#> [1] "2020 Nov"
```

<sup>Created on 2021-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Fuco1** [comment]
Uhm, that's sweet :D Thanks for getting back to my question!
