### ISSUE TITLE
R Session aborted reproducible - after new_data() call

### ISSUE THREAD

**Issue by WoVollmer** [tidyverts/tsibble#193]
After updating R Studio and R to the latest versions
R Studio: Version 1.3.959
R version 4.0.1
Windows 10 platform       x86_64-w64-mingw32 

I got an RStudio abort after a new_data() call.
---

Brief description of the problem

RStudio message:

R Session Aborted
R encountered a fatal error.
The session was terminated.
Start New Session

Finally I could reproduce the issue even with a small change to an example of the the new_data() help documentation. Only adding  group_by(Sensor) to pedestrian.

```r
library(tidyverse)
library(fpp3)
new_data(pedestrian %>% group_by(Sensor), keep_all = TRUE)
```

**Comment by earowang** [comment]
Hmm, I'll investigate on this issue. But you don't need to `group_by()`  for `new_data()`, as the grouping variable is ignored. 

```r
new_data(pedestrian, keep_all = TRUE)
```

will have no problem.
