### ISSUE TITLE
year* ggplot2 scales outside of plot limits

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/tsibble#195]
1970 W1 is shown as a break/label despite not being within the x axis limits on the plot.

``` r
library(tsibble)
#> Warning: package 'tsibble' was built under R version 3.6.3
library(ggplot2)
tsibble(grp = "A", idx = yearweek(1:10), y = rnorm(10), index = idx, key = grp) %>% 
  ggplot(aes(x = idx, y = y)) + 
  geom_line()
```

![](https://i.imgur.com/S9PVT6V.png)

<sup>Created on 2020-06-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by earowang** [comment]
PR please?

Cheers,
Earo
