### ISSUE TITLE
Add fullseq method for year* variants

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/tsibble#198]
The `date_breaks` parameter cannot be used with ggplot2 scales for tsibble time classes.

``` r
library(tsibble)
#> Warning: package 'tsibble' was built under R version 3.6.3
library(ggplot2)
as_tsibble(USAccDeaths) %>% 
  ggplot(aes(x = index, y = value)) + 
  geom_line() + 
  scale_x_yearmonth(date_breaks = "2 years", date_labels = "%Y")
#> Error in UseMethod("fullseq"): no applicable method for 'fullseq' applied to an object of class "c('yearmonth', 'vctrs_vctr')"
```

![](https://i.imgur.com/WTWwSSq.png)

<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by earowang** [comment]
Now the arguments are passed to `scale_x_continuous()`, and `_date()` 
doesn’t give nice default breaks anymore. Maybe you can have some 
suggestions on this.

I’ll submit a patch version soon.

Cheers,
Earo
