### ISSUE TITLE
Filtering "yearmonth" with a dates causes a warning

### ISSUE THREAD

**Issue by markfairbanks** [tidyverts/tsibble#200]
Filtering a column of class "yearmonth" using a date filter now causes a warning. It still seems to work, but the warning is new:

``` r
library(fpp3)

test_df <- tibble(index = yearmonth(ymd(20200101) + months(0:1)))

test_df %>%
  filter(index < ymd(20200201))
#> Warning in mask$eval_all_filter(dots, env_filter): Incompatible methods
#> ("<.vctrs_vctr", "<.Date") for "<"
#> # A tibble: 1 x 1
#>      index
#>      <mth>
#> 1 2020 Jan
```

**Comment by earowang** [comment]
Yep, it's new, and now comparisons between different objects 
(`yearmonth` and `Date`) are no longer encouraged. Since `v0.9.0`, 
tsibble shifts to a more robust framework (`vctrs`) that underlies these 
classes.

Cheers,
Earo

**Comment by markfairbanks** [comment]
Gotcha, makes sense. Thanks for the help
