### ISSUE TITLE
plot.tbl_ts method?

### ISSUE THREAD

**Issue by mpadge** [tidyverts/tsibble#202]
Please feel free to judge this as out-of-scope. It's just a thought raised by @rkillick, and which would personally make sense to me.

### What i would like

Default `plot` on `tsibble` objects to put the `index` axis on the horizontal (unless otherwise specified or controlled).

### Current behaviour

``` r
library (tsibble)
n <- 10
vals <- 1:n
x <- tsibble (y = runif (n),
              time = vals,
              index = time)
plot (x, type = "l")
```

![](https://i.imgur.com/aDgU3MN.png)

The index variable is automatically put on 2nd (y) axis, because it's the 2nd column.

### A solution

(This is nothing like what implemented code should look like, but illustrates the point.)

``` r
plot.tbl_ts <- function (x, ...) {
    i <- match (index_var (x), names (x))
    o <- c (i, seq (ncol (x)) [-i])
    plot.default (x [, o], ...)
}

plot (x, type = "l")
```

![](https://i.imgur.com/CRSvGe9.png)

<sup>Created on 2020-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

There is current no default `plot.tbl_ts` method, for likely very good and understandable reasons. Foremost among these is unintended side effects, which this makes no attempt to anticipate. Nevertheless might be worth thinking about?

**Comment by rkillick** [comment]
Users of `ts` objects would be expecting time on the x-axis as this is the default `plot.ts`.  As Mark states, there may be a reason for not having a separate `plot.tbl_ts` method, but if not then the anticipated behaviour would be time on the x-axis.

**Comment by earowang** [comment]
All graphical methods for tsibble are available in the {[feasts}](https://feasts.tidyverts.org) package. We provide `autoplot()` for time series plots using ggplot, instead of `plot()`.
