### ISSUE TITLE
vctrs conflicting with tsibble?

### ISSUE THREAD

**Issue by EconProf** [tidyverts/tsibble#203]
I get an error using tsibble with the  latest development versions of vctrs (the June 23 and June 24 commits). Reverting vctrs back to the June 18 version gives a normal result. Same error message for as_tsibble() and update_tsibble().

A conflict between the development version of vctrs and tsibble?
---

An example using code from Chapter 5 in fpp3:

``` r
library(fpp3)      

google_stock <- gafa_stock %>%
  filter(Symbol == "GOOG") %>% 
  mutate(day = row_number()) %>%
  update_tsibble(index = day, regular = TRUE)
#> Error: `...` is not empty.
#> 
#> We detected these problematic arguments:
#> * `relax`
#> 
#> These dots only exist to allow future extensions and should be empty.
#> Did you misspecify an argument?
```

<sup>Created on 2020-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by earowang** [comment]
The latest {vctrs} dev breaks dplyr code, and hence tsibble. The {vctrs} team will get it fixed.

``` r
library(tsibbledata)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
google_stock <- gafa_stock %>%
  filter(Symbol == "GOOG") %>% 
  mutate(day = row_number()) %>%
  as_tibble() %>% 
  arrange(day)
#> Error: `...` is not empty.
#> 
#> We detected these problematic arguments:
#> * `relax`
#> 
#> These dots only exist to allow future extensions and should be empty.
#> Did you misspecify an argument?
```

<sup>Created on 2020-06-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
