### ISSUE TITLE
yearweek with varying start day 

### ISSUE THREAD

**Issue by aspina7** [tidyverts/tsibble#205]
Hello, 

thanks for the very awesome package. 

Just wondering if there has been any discussions around adding options to define first day of the week? 

For example as implemented in the [{aweek}](https://github.com/reconhub/aweek) package. 

Realise you probably have a lot bigger things to think about - but this would just be a "nice to have" for epidemiologists that are working in places and on data where the week does not start on monday. 

Thanks again!

**Comment by TimTaylor** [comment]
This would definitely be a "nice to have".  In the meantime, I ***think*** you can extend tsibble to use aweek as follows:
``` r
library(outbreaks)
library(dplyr, warn.conflicts = FALSE)
library(tsibble)
library(aweek)
library(vctrs)
library(lubridate, warn.conflicts = FALSE)

# bits for tsibble --------------------------------------------------------
index_valid.aweek <- function(x) {
  TRUE
}

interval_pull.aweek <- function(x) {
  wk <- as.double((as_date(x) - as_date("1969-12-29")) / 7)
  nweeks <- tsibble:::gcd_interval(wk)
  new_interval(week = nweeks)
}

vec_cast.double.aweek <- function(x, to, ...) {
  as.double((as_date(x) - as_date("1969-12-29")) / 7)
}


# load data ---------------------------------------------------------------
dat_raw <- ebola_sim_clean$linelist

dat_ts <-
  dat_raw %>%
  as_tsibble(key = case_id, index = date_of_onset)


# aweek epiweek version ---------------------------------------------------
dat_ts %>%
  group_by(hospital, outcome) %>%
  index_by(epiweek = ~ date2week(., week_start = "Sunday", floor_day = TRUE)) %>%
  group_by(hospital, outcome) %>%
  summarise(count = n())
#> # A tsibble: 849 x 4 [1W]
#> # Key:       hospital, outcome [18]
#> # Groups:    hospital [6]
#>    hospital           outcome epiweek    count
#>    <fct>              <fct>   <aweek>    <int>
#>  1 Connaught Hospital Death   2014-W22-1     3
#>  2 Connaught Hospital Death   2014-W23-1     3
#>  3 Connaught Hospital Death   2014-W24-1     1
#>  4 Connaught Hospital Death   2014-W25-1     6
#>  5 Connaught Hospital Death   2014-W26-1     4
#>  6 Connaught Hospital Death   2014-W27-1     1
#>  7 Connaught Hospital Death   2014-W28-1     4
#>  8 Connaught Hospital Death   2014-W29-1     6
#>  9 Connaught Hospital Death   2014-W30-1     4
#> 10 Connaught Hospital Death   2014-W31-1    12
#> # … with 839 more rows
```

<sup>Created on 2020-07-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by earowang** [comment]
Yes, now I think `yearweek()` doesn't have to stick with ISO week. This issue together with #174 can be grouped for shipping together some time.

Regarding {aweek}, since it doesn't support `seq()` and `+` arithmetics, `new_data()` and `*_gaps()` will not work, although the interval support is made possible using the code above.

**Comment by earowang** [comment]
It also reminds me of exporting `gcd_interval()`. Thanks @tjtnew
