### ISSUE TITLE
Transform interval to duration object

### ISSUE THREAD

**Issue by denrou** [tidyverts/tsibble#206]
Hi,

It regularly happens that I need to extract the interval of a tsibble. The `interval_pull` or `interval` works fine but the `interval` object in output does not play nicely with `lubridate`.

It would be nice if `lubridate::as.duration` could handle `interval` objects from tsibble.
One way of doing so would be to extend the S4 method to convert the interval object to a duration object.

In some of my packages, here's what I use:

``` r
library(tsibble)
library(lubridate)
#> 
#> Attachement du package : 'lubridate'
#> The following object is masked from 'package:tsibble':
#> 
#>     interval
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union

SECONDS_IN_UNIT <- list(
  year        = 60 * 60 * 24 * 365.25,
  quarter     = 60 * 60 * 24 * 365.25 / 4,
  month       = 60 * 60 * 24 * 365.25 / 12,
  week        = 60 * 60 * 24 * 7,
  day         = 60 * 60 * 24,
  hour        = 60 * 60,
  minute      = 60,
  second      = 1,
  millisecond = 1e-3,
  microsecond = 1e-6,
  nanosecond  = 1e-9
)

setClass("interval")

setMethod("as.duration", signature(x = c("interval")), function(x, ...) {
  as.duration(sum(sapply(names(SECONDS_IN_UNIT), function(unit) {
    x[[unit]] * SECONDS_IN_UNIT[[unit]]
  })))
}
)

as.duration(tsibble::interval(as_tsibble(AirPassengers)))
#> [1] "2629800s (~4.35 weeks)"
```

<sup>Created on 2020-07-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Is there a better way to do it ? Is this something you think of implementing someday?

Thank you

**Comment by earowang** [comment]
Sure, also for `as.period()`.

**Comment by earowang** [comment]
``` r
lubridate::as.duration(tsibble::new_interval(month = 1))
#> [1] "2629800s (~4.35 weeks)"
```

Please let me know if there are unexpected results.

<sup>Created on 2020-07-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Currently having CRAN warnings for undocumented S4 classes/methods. Will look at it later.

**Comment by denrou** [comment]
Works like a charm!

Thank you
