### ISSUE TITLE
plots in e8bdf05

### ISSUE THREAD

**Issue by EconProf** [tidyverts/tsibble#209]
This error message appears when using autoplot() or ggplot() after installing today's tsibble commit. No error after reverting to ff47615.

``` r
library(fpp3)

us_change %>% autoplot(Consumption)
#> Error in yr[mth0 | mth1] <- yr[mth0 | mth1] - 1: NAs are not allowed in subscripted assignments
```

![](https://i.imgur.com/pRVAmCr.png)

<sup>Created on 2020-07-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by earowang** [comment]
Thanks. Will fix it soon.

Cheers,
Earo
