### ISSUE TITLE
pkgdown-generated documentation seems to be out of date for both the dev and CRAN versions

### ISSUE THREAD

**Issue by jrosen48** [tidyverts/tsibble#213]
Hi, and thanks for a fantastic package!

pkgdown-generated documentation seems to be out of date for both the dev and CRAN versions for [`fill_gaps()`](https://tsibble.tidyverts.org/reference/fill_gaps.html). Specifically, the `id()` function does not appear in either the development or CRAN version of the package. In the development version, a message notes the following:

```{r}
Error: `id()` was deprecated in dplyr 0.5.0 and is now defunct.
Please use `vctrs::vec_group_id()` instead.
```

**Comment by earowang** [comment]
`tsibble::id()` has been removed for about a year. The error msg related to `id()` is from dplyr. The pkgdown website is up-to-date. The resources you refer to might be out-of-date.

**Comment by jrosen48** [comment]
got it, sorry for my confusion!
