### ISSUE TITLE
Allow scale_*()$trans$breaks methods to accept the number of breaks, `n`.

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/tsibble#216]
Most (all?) ggplot2 scale breaks allow `n` to determine the number of breaks
``` r
ggplot2::scale_x_date()$trans$breaks
#> function (x, n = n_default) 
#> {
#>     breaks <- pretty(x, n, ...)
#>     names(breaks) <- attr(breaks, "labels")
#>     breaks
#> }
#> <bytecode: 0x560a5d412e68>
#> <environment: 0x560a5d40f8c0>
```

Scales from {tsibble} do not allow this option to `pretty()`
```r
tsibble::scale_x_yearmonth()$trans$breaks
#> function(x) {
#>       yearmonth(scales::breaks_pretty()(as_date(x)))
#>     }
#> <bytecode: 0x560a5e7b3828>
#> <environment: 0x560a5e7b7c18>
```

<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by earowang** [comment]
Seems that there's no the argument of `n` in `scale_x_date*()` in {ggplot2}?

    library(tsibble)
    library(ggplot2)

    pedestrian %>% 
      dplyr::filter(Sensor == "Southern Cross Station") %>% 
      ggplot(aes(x = Date_Time, y = Count)) +
      geom_line() +
      scale_x_datetime(n = 3)

![](https://i.imgur.com/wF64muU.png)

<sup>Created on 2020-08-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mitchelloharawild** [comment]
I think it can get passed in from somewhere, but I forget where (possibly by changing `n_default`?). I use it internally for changing the number of breaks that are automatically selected.

**Comment by earowang** [comment]
Can you provide a `scale_x_date()` example that uses `n`?

**Comment by earowang** [comment]
Does the new commit resolve your issue?

    tsibble::scale_x_yearmonth()$trans$breaks
    #> function(x) {
    #>     yearmonth(scales::breaks_pretty(n)(as_date(x)))
    #>   }
    #> <bytecode: 0x7fdeb2e89cd8>
    #> <environment: 0x7fdeb2e86288>

<sup>Created on 2020-09-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mitchelloharawild** [comment]
What's the issue with also accepting `n` as a parameter?

``` r
ggplot2::scale_x_date()$trans$breaks
#> function (x, n = n_default) 
#> {
#>     breaks <- pretty(x, n, ...)
#>     names(breaks) <- attr(breaks, "labels")
#>     breaks
#> }
#> <bytecode: 0x55f35ec2c068>
#> <environment: 0x55f35ec263b0>
```

<sup>Created on 2020-09-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by earowang** [comment]
The {scales} package doesn’t provide that kind of api.

Cheers,
Earo
