### ISSUE TITLE
yearquarter start

### ISSUE THREAD

**Issue by StuieT85** [tidyverts/tsibble#217]
The place I work at uses quarters differently than yearquarter, for example, the date 2020-04-01 would be the start of Q1 in 2020, but if I use yearquarter it shows 2021 Q1. I was wondering if there could be some sort of option to set if the year is set at the start of the year or at the end.

```r
library(tsibble)

date <- as.Date('2020-04-01')
yearquarter(date, fiscal_start = 3)
```

**Comment by earowang** [comment]
`yearquarter` only handles fiscal year. If the fiscal year starts in March, `2020-03-01` will be 2021 Q1, which `lubridate::quarter()` agrees on. 

```r
date <- as.Date('2020-04-01')
lubridate::quarter(date, with_year = TRUE, fiscal_start = 2)
#> [1] 2021.1
```
<sup>Created on 2020-08-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by StuieT85** [comment]
I figured as much, I will just have to continue to do what I am doing at the moment which is create a function that converts a yearquarter back into a date, subtracts one year and then return it to a yearquarter, just need to remember to do it prior to presenting to bosses.

Honestly, thanks for creating a great package.

**Comment by earowang** [comment]
To make maintenance  easier, we'll stick to the fiscal year convention.
