### ISSUE TITLE
using `as_tsibble`, NAs appear to cause a C stack error

### ISSUE THREAD

**Issue by njtierney** [tidyverts/tsibble#229]
When using `as_tsibble`, in this dataset with NA values, there appears to be an issue with converting it into a `tsibble`. Possibly related to #197

    example_data <- tibble::tribble(
      ~year,                           ~unit_name, ~visitors,
       1939,             "Badlands National Park",    205100,
         NA,       "Honouliuli National Monument",        NA,
       1934, "Fort Donelson National Battlefield",     27127
      )

    library(tsibble)
    library(tidyr)

    example_data %>% 
      drop_na() %>% 
      as_tsibble(key = unit_name,
                 index = year)
    #> # A tsibble: 2 x 3 [5Y]
    #> # Key:       unit_name [2]
    #>    year unit_name                          visitors
    #>   <dbl> <chr>                                 <dbl>
    #> 1  1939 Badlands National Park               205100
    #> 2  1934 Fort Donelson National Battlefield    27127

<sup>Created on 2020-10-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Mojave 10.14.6        
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_AU.UTF-8                 
    #>  ctype    en_AU.UTF-8                 
    #>  tz       Australia/Melbourne         
    #>  date     2020-10-20                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version    date       lib source                            
    #>  anytime       0.3.9      2020-08-27 [1] CRAN (R 4.0.2)                    
    #>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.0)                    
    #>  backports     1.1.10     2020-09-15 [1] CRAN (R 4.0.2)                    
    #>  callr         3.5.1      2020-10-13 [1] CRAN (R 4.0.2)                    
    #>  cli           2.1.0      2020-10-12 [1] CRAN (R 4.0.2)                    
    #>  crayon        1.3.4      2017-09-16 [1] CRAN (R 4.0.0)                    
    #>  desc          1.2.0      2018-05-01 [1] CRAN (R 4.0.0)                    
    #>  devtools      2.3.2      2020-09-18 [1] CRAN (R 4.0.2)                    
    #>  digest        0.6.26     2020-10-17 [1] CRAN (R 4.0.2)                    
    #>  dplyr         1.0.2      2020-08-18 [1] CRAN (R 4.0.0)                    
    #>  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.0.0)                    
    #>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.0.0)                    
    #>  fansi         0.4.1      2020-01-08 [1] CRAN (R 4.0.0)                    
    #>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.0.2)                    
    #>  generics      0.0.2      2018-11-29 [1] CRAN (R 4.0.0)                    
    #>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                    
    #>  highr         0.8        2019-03-20 [1] CRAN (R 4.0.0)                    
    #>  htmltools     0.5.0      2020-06-16 [1] CRAN (R 4.0.1)                    
    #>  knitr         1.30       2020-09-22 [1] CRAN (R 4.0.2)                    
    #>  lifecycle     0.2.0      2020-03-06 [1] CRAN (R 4.0.0)                    
    #>  lubridate     1.7.9      2020-06-08 [1] CRAN (R 4.0.0)                    
    #>  magrittr      1.5        2014-11-22 [1] CRAN (R 4.0.2)                    
    #>  memoise       1.1.0      2017-04-21 [1] CRAN (R 4.0.0)                    
    #>  pillar        1.4.6      2020-07-10 [1] CRAN (R 4.0.2)                    
    #>  pkgbuild      1.1.0      2020-07-13 [1] CRAN (R 4.0.2)                    
    #>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.0.0)                    
    #>  pkgload       1.1.0      2020-05-29 [1] CRAN (R 4.0.0)                    
    #>  prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.0.0)                    
    #>  processx      3.4.4      2020-09-03 [1] CRAN (R 4.0.2)                    
    #>  ps            1.4.0      2020-10-07 [1] CRAN (R 4.0.2)                    
    #>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.0.0)                    
    #>  R6            2.4.1      2019-11-12 [1] CRAN (R 4.0.0)                    
    #>  Rcpp          1.0.5      2020-07-06 [1] CRAN (R 4.0.0)                    
    #>  remotes       2.2.0      2020-07-21 [1] CRAN (R 4.0.2)                    
    #>  rlang         0.4.8      2020-10-08 [1] CRAN (R 4.0.2)                    
    #>  rmarkdown     2.3.8      2020-09-22 [1] Github (rstudio/rmarkdown@fbd0b1f)
    #>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 4.0.0)                    
    #>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.0)                    
    #>  stringi       1.5.3      2020-09-09 [1] CRAN (R 4.0.2)                    
    #>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.0.0)                    
    #>  testthat      2.3.2      2020-03-02 [1] CRAN (R 4.0.0)                    
    #>  tibble        3.0.4      2020-10-12 [1] CRAN (R 4.0.2)                    
    #>  tidyr       * 1.1.2      2020-08-27 [1] CRAN (R 4.0.2)                    
    #>  tidyselect    1.1.0      2020-05-11 [1] CRAN (R 4.0.0)                    
    #>  tsibble     * 0.9.3.9000 2020-10-18 [1] Github (tidyverts/tsibble@c389df4)
    #>  usethis       1.9.0.9000 2020-09-22 [1] Github (r-lib/usethis@57d95a5)    
    #>  utf8          1.1.4      2018-05-24 [1] CRAN (R 4.0.0)                    
    #>  vctrs         0.3.4      2020-08-29 [1] CRAN (R 4.0.2)                    
    #>  withr         2.3.0      2020-09-22 [1] CRAN (R 4.0.2)                    
    #>  xfun          0.18       2020-09-29 [1] CRAN (R 4.0.2)                    
    #>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.0.0)                    
    #> 
    #> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

But if using data that has NA values, I get this

```
> example_data %>% 
+   as_tsibble(key = unit_name,
+              index = year)
Error: C stack usage  7971536 is too close to the limit
```

**Comment by earowang** [comment]
Thanks. I'll look into this issue. But tsibble doesn't accept `NA` in the index column, and the expected error message is that `index must not contain NA`.

**Comment by njtierney** [comment]
Thanks, @earowang !
