### ISSUE TITLE
Could you incorporate tibbletime::as_period() functionality? 

### ISSUE THREAD

**Issue by GitHunter0** [tidyverts/tsibble#230]
`tibbletime::as_period()` has a highly useful functionality that I cannot find elsewhere.
Would you develop something like that in `tsibble`? I believe it would complement very well the other `tsibble `functions.
Thanks a lot.

**Comment by earowang** [comment]
You may find {lubridate} useful. The {luridate} provides many `as_period()` functionality and beyond, like `floor_date()` https://lubridate.tidyverse.org/reference/round_date.html
