### ISSUE TITLE
`is_regular_interval` failing to detect regular interval

### ISSUE THREAD

**Issue by davidtedfordholt** [tidyverts/tsibble#231]
When I feed tsibbles into `is_regular_interval()`, I get `Error: Detecting a corrupt tsibble object, and please reconstruct with as_tsibble().` This includes a tsibble I just created with `regular = TRUE`.

Using `tsibble 0.9.3` and `R 4.0.3`

```r
tibble(x = 1:10, y = seq.Date(as.Date('2020-01-01'), by = 'day', length.out = 10)) %>% 
    as_tsibble(index = y, regular = TRUE) %>% 
    is_regular_interval()
```

**Comment by earowang** [comment]
Thanks. I removed that misleading error message. The `is_regular_interval()` expects an `interval` object instead of `tsibble`.
