### ISSUE TITLE
Suggestion: Mention "panel data" and "longitudinal data" in the documentation

### ISSUE THREAD

**Issue by GitHunter0** [tidyverts/tsibble#234]
Nowhere in the documentation I saw the terms "panel data" and "longitudinal data", which are key to convey what `tsibble` is specially useful for in R. I believe mentioning that would draw the attention of many more researchers of several areas. Just a suggestion. Thank you.

**Comment by earowang** [comment]
Would you be interested in submitting a PR that you think where we could mention "panel data" and "longitudinal data"?

**Comment by GitHunter0** [comment]
For sure @earowang , I will soon make a suggestion in a PR. Thanks

**Comment by GitHunter0** [comment]
https://github.com/tidyverts/tsibble/pull/243

**Comment by earowang** [comment]
Thanks. I thought you refer to some functions that are useful for panel data. If you mean readme, I intentionally use "temporal data" in the readme, to (hopefully) encompass panel data and time series.
