### ISSUE TITLE
interval_pull.POSIXt > new_interval is missing arguments for all intervals above hour

### ISSUE THREAD

**Issue by yogat3ch** [tidyverts/tsibble#237]
[interval_pull.POSIXt](https://github.com/tidyverts/tsibble/blob/863a214b23d185ac1f33dc52a1d43661966fe7b2/R/interval.R#L34) fails when the input vector has interval greater than one hour.

Reprex: 
```
tsibble::interval_pull(lubridate::as_datetime(c("2020-03-30", "2020-03-31", "2020-04-01")))
```

To fix: #236

**Comment by earowang** [comment]
If it's daily data, we suggest to use `Date` to represent instead of `POSIXct`, which has been documented in https://tsibble.tidyverts.org/reference/tsibble-package.html#index and https://tsibble.tidyverts.org/articles/faq.html

**Comment by yogat3ch** [comment]
Ok, thanks for sharing the FAQ! I'll re-work my package using these specialized time classes and see if everything works out.
