### ISSUE TITLE
Automatically 'arrange' after a join with tsibble

### ISSUE THREAD

**Issue by pgg1309** [tidyverts/tsibble#247]
When joining two tsibbles, the outcome may be in the 'wrong order'. Since tsibble is used for time series, it would be nice if the outcome of any join could be automatically sorted (arrange) by the index, or key/index pair. 

```r
x <- rnorm(100)
x <- cumsum(x)
dt <- tsibble::yearquarter("1950 Q1")
dt <- seq(dt, by = 1, along.with = x)
A <- as_tsibble(tibble(index = dt, x = x))

y <- cumsum(rnorm(30))
B <- as_tsibble(tibble(index = dt[25:54], y = y)) 

Z <- full_join(B, A)
head(Z)
head(arrange(Z, index))
```

**Comment by earowang** [comment]
Thanks. Yes, it should re-arrange the joined outcome.
