### ISSUE TITLE
build_tsibble_meta ordered argument is not handled as documentation states

### ISSUE THREAD

**Issue by yogat3ch** [tidyverts/tsibble#248]
Hi tsibble devs,
I wanted bring to your attention that the docs for `build_tsibble_meta` state the following for the `ordered` argument:

> The default of NULL arranges the key variable(s) first and then index from past to future. TRUE suggests to skip the ordering as x in the correct order. FALSE checks the ordering and may give a warning.

However, the first line of code inside of `build_tsibble_meta` is `stopifnot(!is.null(ordered))` making it such that it errors whenever `ordered = NULL`.

I'm think this is probably because the function is inheriting parameters from `build_tsibble` and the functionality now no longer matches the entry for that parameter.

Thanks!

**Comment by earowang** [comment]
Thanks. Will fix the docs soon

**Comment by yogat3ch** [comment]
Thank you!
