### ISSUE TITLE
max does not return maximum yearmonth from passed arguments

### ISSUE THREAD

**Issue by Fuco1** [tidyverts/tsibble#257]
Taking a max of two yearmonths, the smaller (earlier) is returned.

```r
> max(yearmonth('2017-01-01'), yearmonth('2018-04-01'))
<yearmonth[1]>
[1] "2017 Jan"
```

However, taking a max of two date objects, the bigger (later) is correctly returned.

```r
> max(as.Date('2017-01-01'), as.Date('2018-04-01'))
[1] "2018-04-01"
> 
```

**Comment by mitchelloharawild** [comment]
This is an inherited from the {vctrs} package, the relevant issue for this is here: https://github.com/r-lib/vctrs/issues/1372


Passed via `…`

``` r
library(tsibble)
max(yearmonth('2017-01-01'), yearmonth('2018-04-01'))
#> <yearmonth[1]>
#> [1] "2017 Jan"
```

Passed via `..1` (`x`)

``` r
max(c(yearmonth('2017-01-01'), yearmonth('2018-04-01')))
#> <yearmonth[1]>
#> [1] "2018 Apr"
```

<sup>Created on 2021-05-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by Fuco1** [comment]
I see.  I suppose we can close this issue then, unless you want to use it as a soft pressure device for the upstream :D Thanks for the heads up!
