### ISSUE TITLE
Provide knit_print method for tbl_ts

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/tsibble#26]
Currently when displaying a tsibble object in R markdown it defaults to data.frame.

For better output, something similar to tibble's knit_print method is needed:
```r 
tibble::knit_print.trunc_mat
```

**Comment by earowang** [comment]
Can you provide a snapshot by defaulting to data.frame? README is an Rmarkdown file, and it seems to me it displays as a tsibble object instead of data.frame.

**Comment by mitchelloharawild** [comment]
On closer inspection, it seems to work okay.
tsibbledata should have tsibble as a dependency instead.
