### ISSUE TITLE
pkgdown pages for ?yearquarter and ?yearweek missing

### ISSUE THREAD

**Issue by krlmlr** [tidyverts/tsibble#265]
- https://tsibble.tidyverts.org/reference/yearweek.html
- https://tsibble.tidyverts.org/reference/yearquarter.html
- https://tsibble.tidyverts.org/dev/reference/yearweek.html
- https://tsibble.tidyverts.org/dev/reference/yearquarter.html

**Comment by earowang** [comment]
Not missing
* https://tsibble.tidyverts.org/reference/year-week.html
* https://tsibble.tidyverts.org/reference/year-quarter.html
