### ISSUE TITLE
Broken links from ?yearmonth

### ISSUE THREAD

**Issue by krlmlr** [tidyverts/tsibble#266]
https://tsibble.tidyverts.org/reference/year-month.html points to https://tsibble.tidyverts.org/reference/yearquarter.html in its "See also" section, but should point to https://tsibble.tidyverts.org/reference/year-quarter.html. Same for yearweek.

Is this an artifact of a recent file name change for `.Rd`? Or a pkgdown bug?

**Comment by earowang** [comment]
Seems {pkgdown} dev fixes this issue.
