### ISSUE TITLE
Support for `stats::start()` and `stats::end()` in `fill_gaps()`

### ISSUE THREAD

**Issue by wkdavis** [tidyverts/tsibble#269]
The checks for the `.full` argument of `fill_gaps()` don't support using `stats::start()` and `stats::end()`

https://github.com/tidyverts/tsibble/blob/bfeae843f56328645a188a0c4acef1598b285f99/R/gaps.R#L167

https://github.com/tidyverts/tsibble/blob/bfeae843f56328645a188a0c4acef1598b285f99/R/gaps.R#L171

which necessitates using `#' @importFrom stats start end` if `fill_gaps()` is being used inside another package.

Conceptually it seems like a minor change but I couldn't think of an elegant solution. Is this something you would be willing to support?

**Comment by earowang** [comment]
Thanks. Fixed.

**Comment by wkdavis** [comment]
Thank you!
