### ISSUE TITLE
Error when arranging a tsibble

### ISSUE THREAD

**Issue by paulponcet** [tidyverts/tsibble#273]
When running the following code: 

    library(dplyr)
    library(tsibble)
    toto <- tsibble(K = c("A", "A", "B", "B"), I = c(1, 2, 1, 2), key = K, index = I)
    arrange(toto, I)

I get the following error: 

    Error in `summarise()`:
    ! Problem while computing `.rows = any(validate_order_lst(indices, .rows))`.
    Caused by error in `f()`:
    ! 3 arguments passed to .Internal(is.unsorted) which requires 2

Could this be related to the recent `dplyr` updates (version 1.0.8)? 
Thx

------------

Here is my session info: 

    R version 4.1.1 (2021-08-10)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows Server x64 (build 17763)
    
    Matrix products: default
    
    locale:
    [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] dplyr_1.0.8   tsibble_1.1.1

**Comment by StatKalli** [comment]
Hi, this can be solved by updating your R version to  `4.1.2`, this was already mentioned 2 months ago here: https://githubhot.com/repo/Bioconductor/S4Vectors/issues/95

**Comment by earowang** [comment]
Have you resolved this issue? Can't reproduce this on my side.

**Comment by earowang** [comment]
Feel free to reopen it. If this issue persists.
