### ISSUE TITLE
Loading the {tsibble} package causes an error with {stats}

### ISSUE THREAD

**Issue by AndrewKostandy** [tidyverts/tsibble#277]
Thank you for your great work with the {tsibble} package.

There appears to be an issue where loading the {tsibble} package (or running some functions from it) causes an error with the {stats} package. This in turn causes an error in other packages that use {stats} such as the {CausalImpact} package.

Below is a reprex from a response post of a collaborator in the {CausalImpact} repo:

This works:
```r
dates <- as.Date(c("2022-01-01", "2022-01-08"))
stats::window(dates, 1)
```

This fails:
```r
library(tsibble)
stats::window(dates, 1)
```
Error in seq.int(trunc((start - xtsp[1L]) * xfreq + 1.5), trunc((end - :
'from' must be of length 1

You can also see how this issue causes a problem with the {CausalImpact} package by reading from the below comment onwards: https://github.com/google/CausalImpact/issues/32#issuecomment-1038264276

**Comment by earowang** [comment]
Sorry for taking so long to responds. Yes, can confirm {tsibble} overwriting the `time()` function here, that causes the problem. Will fix it soon.
