### ISSUE TITLE
yearquarter format

### ISSUE THREAD

**Issue by arnaud-feldmann** [tidyverts/tsibble#279]
Yearquarter strings usually depend of locale. That is, in my language (French), the dates would often be in in the "2020T4" format (T for _trimestre_)

Could it be possible to get a format arg ?

```r
yearquarter("2020T4")
#<yearquarter[1]>
#[1] "2020 Q2"
yearquarter("2020Q4")
#<yearquarter[1]>
#[1] "2020 Q4"
```

**Comment by earowang** [comment]
You can use the `format` arg in the `format()` function to have the desired display, but not the input of `yearquarter()`.

``` r
format(tsibble::yearquarter("2020T4"), format = "%YT%q")
#> [1] "2020T2"
```

<sup>Created on 2022-10-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
