### ISSUE TITLE
Sliding Correlation 

### ISSUE THREAD

**Issue by alexhallam** [tidyverts/tsibble#33]
I really like the `slide()` function in this package. The documentation shows a moving average as follows: 

`mutate(temp_ma = slide(temp, ~ mean(., na.rm = TRUE), size = 3))`

Is their documentation showing how to supply two variables so a moving correlation may be calculated?

Maybe something like the following?

`mutate(temp_ma = slide(y=temp, x=time_hour, ~ cor(., na.rm = TRUE), size = 3))`

**Comment by earowang** [comment]
that’s a very good point, which I haven’t thought before. I’ll add them for next release.

**Comment by earowang** [comment]
I've added `slide2()` to handle two variables:

```r
mutate(temp_ma = slide2(.y=temp, .x=time_hour, ~ cor(.x, .y, na.rm = TRUE), .size = 3))
```

I've also renamed the arguments to `.x`, `.y`, and `.size` in order to be consistent with `purrr::map2()`.

**Comment by alexhallam** [comment]
Thanks for adding this feature. Also, your consistancy with `purrr::map2()` is much appreciated.
