### ISSUE TITLE
Suggestion to follow the `purrr` interface exactly with window functions for max flexibility

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverts/tsibble#35]
Hi @earowang, hope things are well. I really like your set of `slide`, `tile` & `stretch` functions. I was just experimenting with them, and noticed how it partially follows `purrr`. Would you be open to completely following the `purrr` syntax? 

Here is my motivating mini-example showing there are cases where you might want to return a lgl rather than a numeric from `slide2()`. It compares a 5 day moving average of `open` and `close` stock prices and could be a "useful" indicator.

``` r
library(tsibble)

data("FANG", package = "tibbletime")

FANG %>%
  group_by(symbol) %>%
  mutate(rolling_lgl_compare = slide2(open, close, ~ mean(open) > mean(close), .size = 5)) %>%
  select(symbol, open, close, rolling_lgl_compare)
#> # A tibble: 4,032 x 4
#> # Groups:   symbol [4]
#>    symbol  open close rolling_lgl_compare
#>    <chr>  <dbl> <dbl>               <dbl>
#>  1 FB      27.4  28                    NA
#>  2 FB      27.9  27.8                  NA
#>  3 FB      28.0  28.8                  NA
#>  4 FB      28.7  29.4                  NA
#>  5 FB      29.5  29.1                   1
#>  6 FB      29.7  30.6                   1
#>  7 FB      30.6  31.3                   1
#>  8 FB      31.3  31.7                   1
#>  9 FB      32.1  31.0                   1
#> 10 FB      30.6  30.1                   1
#> # ... with 4,022 more rows
```

With the current implementation, we can't go straight to `logical` which is what I wanted.

If I could suggest a solution, I would make `slide2()` do what `slide2_lst()` does, and then add `slide2_dbl()`, `slide2_lgl()` and so on. Similar with the other window functions. This would follow `purrr` exactly. I might even be able to then create a `furrr` style interface on top of that to run this in parallel for large datasets!!

If you are worried about package bloat, which is valid, you could also consider splitting these 3 incredibly useful and generic functions and all of their variants into their own package. It would only depend on `purrr` and `rlang` as far as I can tell. Other people might want to use them without the full `tsibble` package since you don't need a `tsibble` object.

Let me know what you think! Great work!

**Comment by DavisVaughan** [comment]
If you think any of this is a good idea, I'd be happy to help implement and submit a PR.

**Comment by earowang** [comment]
Following `purrr` exactly sounds a great idea. would be delighted to receive a PR on other variants. Thanks.

**Comment by earowang** [comment]
I'm looking to release the next version in a week or so. when could the PR be done? If you're busy, I'm happy to implement it myself.

**Comment by DavisVaughan** [comment]
I just started my first "real job" so got a bit busier. I'll focus on this tonight!

**Comment by earowang** [comment]
Hi Davis, just let you know I'm going to do this myself today, since I need to make slides for useR!2018 based on the next release. Thanks for your suggestions, and your suggestions on other issues/PRs are welcome.

**Comment by DavisVaughan** [comment]
I'm really sorry I couldn't stick to my word here. Work is keeping me later than expected each day. Thanks for picking up the slack. I hope to stay involved going forward!

**Comment by DavisVaughan** [comment]
Finally getting a minute to look at your updates. With the way you export the variants (besides `_dbl`), they don't show up in the `Usage` section of the docs. Is this a problem? They are exported and help docs like `?slide2_chr` link correctly, but it seems like `roxygen` doesn't recognize them when creating that section of the docs.

**Comment by earowang** [comment]
Yep, the way I generated the variants cannot create `\usage` sections. So I mentioned the variants in description section, and hope to add more examples too.

**Comment by DavisVaughan** [comment]
Gotcha! Figured you were aware, just wanted to make sure. RStudio auto complete helps too
