### ISSUE TITLE
A "user experience" issue with id()

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverts/tsibble#36]
Hey tidyverts team, 

I've run into a bit of an issue with using `id()` that results from a clash with `dplyr::id()`. When `dplyr` is loaded after `tsibble`, you get this...

``` r
library(tsibble)
library(dplyr)

data("FANG", package = "tibbletime")

# Agh!
FANG %>%
  as_tsibble(key = id(symbol), index = date)
#> Warning: `id()` is deprecated
#> Error: Have you forgotten `tsibble::id()` to create the `key`?

# I needed to do this...
FANG %>%
  as_tsibble(key = tsibble::id(symbol), index = date)
#> # A tsibble: 4,032 x 8 [1DAY]
#> # Keys:      symbol [4]
#>    symbol date        open  high   low close  volume adjusted
#>    <chr>  <date>     <dbl> <dbl> <dbl> <dbl>   <dbl>    <dbl>
#>  1 AMZN   2013-01-02  256.  258.  253.  257. 3271000     257.
#>  2 AMZN   2013-01-03  257.  261.  256.  258. 2750900     258.
#>  3 AMZN   2013-01-04  258.  260.  257.  259. 1874200     259.
#>  4 AMZN   2013-01-07  263.  270.  263.  268. 4910000     268.
#>  5 AMZN   2013-01-08  267.  269.  264.  266. 3010700     266.
#>  6 AMZN   2013-01-09  268.  270.  265.  266. 2265600     266.
#>  7 AMZN   2013-01-10  269.  269.  262.  265. 2863400     265.
#>  8 AMZN   2013-01-11  265.  268.  264.  268. 2413300     268.
#>  9 AMZN   2013-01-14  268   274.  268.  273. 4275000     273.
#> 10 AMZN   2013-01-15  271.  273.  269.  272. 2326900     272.
#> # ... with 4,022 more rows
```

This has the potential to be fairly frustrating for new users, as the error message is not very clear about what has happened. From the dplyr message, I assume `id()` will be removed eventually, but who knows when.

Thinking along the lines of how you might be able to be consistent with `dplyr`:

`dplyr` has) `groups()`, `group_vars()`, and `group_indices()`
`tsibble` has) `key()`, `key_vars()`, and `key_indices()`

To me, it might make sense to rename `key()` as `keys()` to be consistently plural like `groups()`, then you could use `key()` rather than `id()`, which also matches the name of the argument! Thoughts?

**Comment by earowang** [comment]
1. For a grouped data frame, it could have multiple groups, hence using plural makes sense in the `dplyr` context. But a tsibble object, from my understanding, can have only one key either implicit or explicit (something similar to "primary key" in SQL), and the key might be comprised of single or multiple variables, not multiple keys. 
2. `id()` suggests the identifiers that users think to make the key, but it's not necessarily a valid key. But `key()` always returns a valid key as the input is already a tsibble. The distinction needs to be made somehow.
3. I agree the message is very confusing. Maybe a more informative error says clashing with `dplyr::id()`.

**Comment by earowang** [comment]
Now force to use `tsibble::id()` inside of `as_tsibble()`.
``` r
library(tsibble)
#> 
#> Attaching package: 'tsibble'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following object is masked from 'package:tsibble':
#> 
#>     id
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

data("FANG", package = "tibbletime")

# Tada!
FANG %>%
  as_tsibble(key = id(symbol), index = date)
#> # A tsibble: 4,032 x 8 [1DAY]
#> # Keys:      symbol [4]
#>    symbol date        open  high   low close  volume adjusted
#>    <chr>  <date>     <dbl> <dbl> <dbl> <dbl>   <dbl>    <dbl>
#>  1 AMZN   2013-01-02  256.  258.  253.  257. 3271000     257.
#>  2 AMZN   2013-01-03  257.  261.  256.  258. 2750900     258.
#>  3 AMZN   2013-01-04  258.  260.  257.  259. 1874200     259.
#>  4 AMZN   2013-01-07  263.  270.  263.  268. 4910000     268.
#>  5 AMZN   2013-01-08  267.  269.  264.  266. 3010700     266.
#>  6 AMZN   2013-01-09  268.  270.  265.  266. 2265600     266.
#>  7 AMZN   2013-01-10  269.  269.  262.  265. 2863400     265.
#>  8 AMZN   2013-01-11  265.  268.  264.  268. 2413300     268.
#>  9 AMZN   2013-01-14  268   274.  268.  273. 4275000     273.
#> 10 AMZN   2013-01-15  271.  273.  269.  272. 2326900     272.
#> # ... with 4,022 more rows
```

Created on 2018-06-26 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by DavisVaughan** [comment]
Ah, clever use of delayed evaluation and overscoping in eval_tidy()! I like it!

**Comment by DavisVaughan** [comment]
Also I see your point about id() being the identifiers but not necessarily valid. And the comparison to primary keys in SQL makes sense of why you'd use key() and not keys(). Thanks for explaining!
