### ISSUE TITLE
build_tsibble() might be too slow for large amounts of repeated use

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverts/tsibble#43]
This issue originally came up when testing `slider()` when it was allowed to take a data frame and return a list of data frames sliced up by the `.size` variable. I noticed that when using `tbl_ts` objects, this was pretty slow, but when using data frames it was almost instantaneous.

Below is an extreme example, but is one that I think captures the idea. If you profile this, you should see `build_tsibble` as the culprit of at least 16 seconds or so. If memory serves me, I think there may be a way to restructure what get's validated when `validate = FALSE` so `build_tsibble()` does even less in the case when we already know it is going to be a valid `tsibble`, but I need to look more into it.

``` r
library(tsibble)
data("pedestrian")
pedestrian_df <- as.data.frame(pedestrian)

random_rows <- sample(1:nrow(pedestrian), 5000, replace = TRUE)

tic()
fast <- lapply(random_rows, function(row) {pedestrian_df[row, , drop = FALSE]})
toc()
#> 2.241 sec elapsed

tic()
slow <- lapply(random_rows, function(row) {pedestrian[row, , drop = FALSE]})
toc()
#> 23.712 sec elapsed
```

**Comment by earowang** [comment]
Thanks, Davis. 

When subsetting by rows, the interval gets re-computed (one of the major bottlenecks) every time. I've also added early return/exit to some functions, which seems to speed it up a bit. But lots of room to improve in `build_tsibble()`.

``` r
library(tsibble)
#> 
#> Attaching package: 'tsibble'
#> The following object is masked from 'package:stats':
#> 
#>     filter
data("pedestrian")
pedestrian_df <- as.data.frame(pedestrian)
pedestrian_tbl <- as_tibble(pedestrian)

random_rows <- sample(1:nrow(pedestrian), 5000, replace = TRUE)

system.time(
fast <- lapply(random_rows, function(row) {pedestrian_df[row, , drop = FALSE]})
)
#>    user  system elapsed 
#>   0.260   0.002   0.262

system.time(
slow <- lapply(random_rows, function(row) {pedestrian[row, , drop = FALSE]})
)
#>    user  system elapsed 
#>   7.079   0.061   7.306
```

Created on 2018-07-17 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by earowang** [comment]
~ 10 times faster now. I've got a helper function `build_tsibble_meta()`, which I think might be useful for your packages. Please let me know if you want me to export it or not.

``` r
library(tsibble)
pedestrian_df <- as.data.frame(pedestrian)
random_rows <- sample(1:nrow(pedestrian), 5000, replace = TRUE)

system.time(
fast <- lapply(random_rows, function(row) {pedestrian_df[row, , drop = FALSE]})
)
#>    user  system elapsed 
#>   0.272   0.002   0.275

system.time(
slow <- lapply(random_rows, function(row) {pedestrian[row, , drop = FALSE]})
)
#>    user  system elapsed 
#>   1.903   0.006   1.921
```

Created on 2018-07-18 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).
