### ISSUE TITLE
lag(), lead() and difference() for regular series with missingness

### ISSUE THREAD

**Issue by DavisVaughan** [tidyverts/tsibble#55]
Hi `tidyverts` team. I've been painfully working with some grouped time series that are irregular, either because it came that way or because I filtered out bad data along the way.

I would really love to see a `lag()` that respects the periodicity that I am working with. Here is an example, as this is kind of hard to explain:

``` r
library(tsibble)
library(dplyr)


pedestrian <- pedestrian[1:10,]
pedestrian <- pedestrian[-2,]

# There is no 1st hour, so with a lag of 1, 
# we "should" see an NA for the lagged count at hour 2
pedestrian %>%
  mutate(C_lag = lag(Count, 1)) %>%
  mutate(C_lag_2 = c(NA, NA, 567, 264, 139, 77, 44, 56, 113))
#> # A tsibble: 9 x 7 [1h]
#> # Key:       Sensor [1]
#>   Sensor         Date_Time           Date        Time Count C_lag C_lag_2
#> * <chr>          <dttm>              <date>     <int> <int> <int>   <dbl>
#> 1 Birrarung Marr 2015-01-01 00:00:00 2015-01-01     0  1630    NA      NA
#> 2 Birrarung Marr 2015-01-01 02:00:00 2015-01-01     2   567  1630      NA
#> 3 Birrarung Marr 2015-01-01 03:00:00 2015-01-01     3   264   567     567
#> 4 Birrarung Marr 2015-01-01 04:00:00 2015-01-01     4   139   264     264
#> 5 Birrarung Marr 2015-01-01 05:00:00 2015-01-01     5    77   139     139
#> 6 Birrarung Marr 2015-01-01 06:00:00 2015-01-01     6    44    77      77
#> 7 Birrarung Marr 2015-01-01 07:00:00 2015-01-01     7    56    44      44
#> 8 Birrarung Marr 2015-01-01 08:00:00 2015-01-01     8   113    56      56
#> 9 Birrarung Marr 2015-01-01 09:00:00 2015-01-01     9   166   113     113

# For the lag of size 2, the 0th hour should show up in the 2nd hour
# The implicit 1st hour NA should show up in the 3rd hour 
pedestrian %>%
  mutate(C_lag = lag(Count, 2)) %>%
  mutate(C_lag_2 = c(NA, 1630, NA, 567, 264, 139, 77, 44, 56))
#> # A tsibble: 9 x 7 [1h]
#> # Key:       Sensor [1]
#>   Sensor         Date_Time           Date        Time Count C_lag C_lag_2
#> * <chr>          <dttm>              <date>     <int> <int> <int>   <dbl>
#> 1 Birrarung Marr 2015-01-01 00:00:00 2015-01-01     0  1630    NA      NA
#> 2 Birrarung Marr 2015-01-01 02:00:00 2015-01-01     2   567    NA    1630
#> 3 Birrarung Marr 2015-01-01 03:00:00 2015-01-01     3   264  1630      NA
#> 4 Birrarung Marr 2015-01-01 04:00:00 2015-01-01     4   139   567     567
#> 5 Birrarung Marr 2015-01-01 05:00:00 2015-01-01     5    77   264     264
#> 6 Birrarung Marr 2015-01-01 06:00:00 2015-01-01     6    44   139     139
#> 7 Birrarung Marr 2015-01-01 07:00:00 2015-01-01     7    56    77      77
#> 8 Birrarung Marr 2015-01-01 08:00:00 2015-01-01     8   113    44      44
#> 9 Birrarung Marr 2015-01-01 09:00:00 2015-01-01     9   166    56      56
```

Since `tsibble` knows about the periodicity of your data (`1H` in this case), it should be able to handle this kind of thing. 

This is actually something that Stata is really good at. If you happen to have access to it, you could have done something like `tsset Date_Time, hourly` and then lagging variables would have worked like `gen lag_count = l2.Count` which would respect the gap.

I'd imagine that to work in the `tsibble` framework, this would have to be a function that operates on the entire `tsibble` object, rather than on a vector (unlike the current `dplyr::lag()`). This is necessary because it would have to have access to the index information. I'd imagine something like `lag_time(.data, ..., n = 1L, default = NA)` where you can specify multiple cols to lag in `...`

Edit) I'm aware that I could use `fill_na()` first to make the implicit missing values explicit, then I would be fine, but my issue with that is that I am constantly dropping bad information along the way, so I'd likely have to call `fill_na()` each time I did any kind of bad row drop. Also, it has the potential to greatly increase the size of my dataset.

**Comment by DavisVaughan** [comment]
I agree that it would be much more preferable to use a vector based `lag()` than a `tsibble` object based one. It would be annoying to not be able to do something like `mutate(x, y = lag_time(col1, 2) + 2)` which you essentially wouldn't be able to do if it acted on the whole `tsibble` object like `lag_time(x, col1, 2)`.

Would the indices only be applied when a column is extracted from the `tsibble`? Or would they be attributes from the beginning? Only being applied when extracted is likely easier, otherwise you have to keep track of updating the attributes every time the rows change.

That being said, I see how you could override `[.tbl_ts` to ensure the column gets those indices when it is extracted, but how do you know the `col1` column is being "extracted" and needs those indices in something like `mutate(tbl_ts, x = lag(col1))`? I imagine it would have to happen in a `mutate.tbl_ts()` method, where you attach indices to the relevant `tbl_ts` columns before the `mutate()` is applied.

Also, keep in mind that `dplyr::lag()` is not generic, so you'd either have to override it or use a new function name.

**Comment by earowang** [comment]
Update: [dplyr's hybrid evaluation](
https://dplyr.tidyverse.org/articles/internals/hybrid-evaluation.html) seems to provide a solution for the speeding purpose. But it's still unstable to bind their headers in other packages at this stage.

I'd probably re-export `dplyr::lag()` and `dplyr::lead()` in the future. When registering a hybrid handler for each function, it looks for tsibble namespace and then determines what to do with the index.

**Comment by DavisVaughan** [comment]
So you think if you had a similar thing as here, you could differentiate between the `dplyr` hybrid `lag()` and a `tsibble` one?

https://github.com/tidyverse/dplyr/blob/master/src/hybrid_offset.cpp#L97 

As long as people don't get too confused by the fact that the only way to get this "regular series with missingness" lagging capability is by using `mutate()`, it could be a nice solution.

Where do you find evidence of it still being unstable?

**Comment by earowang** [comment]
Finally tackled this issue, inspired by `dplyr::across()` friends.

Would you be okay to take them for a spin? how do they perform on a large data set?

They currently live in https://github.com/tidyverts/tsibble/tree/55/keyed-lag this branch.

``` r
library(tsibble)
library(dplyr)
bench::mark(
  fill_gaps = fill_gaps(pedestrian) %>% group_by_key() %>% mutate(dplyr::lag(Count)),
  keyed_lag = pedestrian %>% mutate(keyed_lag(Count)),
  check = FALSE
)
#> # A tibble: 2 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 fill_gaps   103.4ms  105.9ms      9.44   34.99MB     14.2
#> 2 keyed_lag    19.1ms   20.7ms     47.3     6.36MB     10.5

pedestrian <- pedestrian[1:10,]
pedestrian <- pedestrian[-2,]
pedestrian %>% 
  mutate(
    C_lag = keyed_lag(Count),
    C_lag2 = keyed_lag(Count, n = 2)
  )
#> # A tsibble: 9 x 7 [1h] <Australia/Melbourne>
#> # Key:       Sensor [1]
#>   Sensor         Date_Time           Date        Time Count C_lag C_lag2
#>   <chr>          <dttm>              <date>     <int> <int> <int>  <int>
#> 1 Birrarung Marr 2015-01-01 00:00:00 2015-01-01     0  1630    NA     NA
#> 2 Birrarung Marr 2015-01-01 02:00:00 2015-01-01     2   567    NA   1630
#> 3 Birrarung Marr 2015-01-01 03:00:00 2015-01-01     3   264   567     NA
#> 4 Birrarung Marr 2015-01-01 04:00:00 2015-01-01     4   139   264    567
#> 5 Birrarung Marr 2015-01-01 05:00:00 2015-01-01     5    77   139    264
#> 6 Birrarung Marr 2015-01-01 06:00:00 2015-01-01     6    44    77    139
#> 7 Birrarung Marr 2015-01-01 07:00:00 2015-01-01     7    56    44     77
#> 8 Birrarung Marr 2015-01-01 08:00:00 2015-01-01     8   113    56     44
#> 9 Birrarung Marr 2015-01-01 09:00:00 2015-01-01     9   166   113     56
```

<sup>Created on 2019-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by benzipperer** [comment]
Hi, what ever happened to the keyed_lag/lead suggestion above? I often end up with panel or time series data that are missing rows for time gaps, and lag/lead functions that respect that missingness would be useful. It seemed like the keyed_lag() and keyed_lead() were just the ticket but I was wondering why they were not implemented?
