### ISSUE TITLE
rlang 0.3.0

### ISSUE THREAD

**Issue by lionel-** [tidyverts/tsibble#65]
Hello,

I am planning to send rlang 0.3.0 on Friday 19th. It causes a revdep failure with CRAN tsibble but I see these are already fixed in the dev version. Any chance you could push a patch release before then?

Also I see you're relying a lot on `quo_text()` which is generally not the right function for programming with. `quo_text()` and `quo_name()` are general purpose deparsers that should generally only be used for printing outputs or creating default labels. Are you using `quo_text()` for converting symbols? If so, you probably need `as_string()` instead.

I don't understand the tsibble code well, but AFAICS you're storing index keys as quosures. These are always columns of the tsibble right? In that case it would likely make the code simpler to store it as symbol, then you can use `as_string()`. Or store as string directly and construct symbols when needed.

**Comment by earowang** [comment]
Actually, I'm planning to get a new release on CRAN soon. Should be done by next Friday. :)

Thanks. I'll replace `quo_text()` with `as_string()`.

Index and  key are stored as symbols instead of quosures. I'm wondering which one is preferred in the tidyverse, symbols or strings?

**Comment by earowang** [comment]
Thanks. It's on CRAN now.

**Comment by lionel-** [comment]
Great, thanks!
