### ISSUE TITLE
guess_frequency() on monthly dates

### ISSUE THREAD

**Issue by Gayyam** [tidyverts/tsibble#75]
Thank you for this great package Earo. This has saved me a lot of time of headache in going to and from `data.frame`s to `ts`.

I was expecting a frequency of 12 for dates separated by exactly a month.

```r
> y <- seq(as.Date('2000-01-01'), by = '1 month', length.out = 50)
> tsibble::guess_frequency(y)
[1] 7
```

Please let me know if I'm missing something obvious.

**Comment by earowang** [comment]
`yearmonth()` is a better alternative for monthly data.

``` r
library(tsibble)
#> 
#> Attaching package: 'tsibble'
#> The following object is masked from 'package:stats':
#> 
#>     filter
y <- seq(yearmonth('2000-01'), by = 1, length.out = 50)
guess_frequency(y)
#> [1] 12
```

<sup>Created on 2018-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
