### ISSUE TITLE
Accept xts (with multiple columns)

### ISSUE THREAD

**Issue by dppalomar** [tidyverts/tsibble#80]
Hi, this package is a great initiative and will definitely be very useful. In many applications, one starts with an xts, typically with multiple columns accounting for multiple assets, i.e., a multivariate time series.

It would be great if tsibble could convert such an xts directly into a tsibble (in long format). So far, all the examples that I have seen for tsibble start with a long format data frame. Right not, the only way I see to do this is by manually using timetk and then reshape2::melt or tidyr::gather.

Thanks
Daniel

**Comment by earowang** [comment]
Hi Daniel,

The package [**tsbox**](http://tsbox.help) provides tools to coerce between time series classes, e.g. from xts to tsibble, which you may like to take a look. The `as_tsibble()` method currently supports `ts`/`mts` from wide to long.

**Comment by dppalomar** [comment]
Hi Earo, that's exactly what I needed!
Thanks

**Comment by ggrothendieck** [comment]
This does it without any additional packages other than xts and tsibble which you have to have anyways.


```
 x %>% 
  fortify.zoo(melt = TRUE) %>%
  as_tsibble(index = "Index", key = "Series")
```

**Comment by dppalomar** [comment]
Thanks!  Will try...
