### ISSUE TITLE
tsibble depends on dplry (>= 0.8.0) but only 0.7.8 is available

### ISSUE THREAD

**Issue by friendly** [tidyverts/tsibble#86]
Trying to install tsibble in R 3.5.2 from github gives an error:

    > remotes::install_github("tidyverts/tsibble")
    Downloading GitHub repo tidyverts/tsibble@master
      

    * installing *source* package 'tsibble' ...
    ....
    ** R
    ** data
    *** moving datasets to lazyload DB
    ** inst
    ** byte-compile and prepare package for lazy loading
    Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
      namespace 'dplyr' 0.7.8 is being loaded, but >= 0.8.0 is required
    ERROR: lazy loading failed for package 'tsibble'
    * removing 'C:/R/R-3.5.2/library/tsibble'
    In R CMD INSTALL
    Error in i.p(...) : 
      (converted from warning) installation of package ‘C:/Users/Friendly/AppData/Local/Temp/Rtmpi6xsnZ/filedd012f1592f/tsibble_0.7.0.tar.gz’ had non-zero exit status

**Comment by earowang** [comment]
I thought this would lead to download and install dplyr dev version (v0.8.0) first and then tsibble, because I've specified the `Remotes` field to use dplyr dev. If prompting to update other packages, can you select the option to update dplyr?

**Comment by friendly** [comment]
Does the github version of tsibble **necessarily** depend on v. 0,8.0 of dplyr on github rather than the CRAN version? 
On Win, R Gui I get a small prompt window that seems to offer only dplyr 0.7.8

**Comment by earowang** [comment]
Yep, I've defined some new `group_*` generics from `v0.8.0` for tsibble to ensure they also work seamlessly with tsibble. The breaking changes in dplyr's grouped data frame also leads to the changes in tsibble's data structure.

Dplyr `v0.8.0` has been submitted to CRAN a couple of days ago, and I think they are going through some CRAN checks and will be on CRAN soon. I'll put tsibble `v0.7.0` on CRAN later this week or next week, when dplyr lands on CRAN.

**Comment by earowang** [comment]
Dplyr and tsibble both are on CRAN now.
