### ISSUE TITLE
droplevels error

### ISSUE THREAD

**Issue by derekholmes** [tidyverts/tsibble#87]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Droplevels drops an error with a tsibble.
(As an additional issue.  key conflicts with data.table::key.  Too late to change it, but kind of unfortunate)

```r
tbl1 <- tibble(
     date = as.Date("2017-01-01") + 0:9,
     thisfactor=factor(rep("A",10),levels=c("A","B")),
     value = rnorm(10)
 )
test1=as_tsibble(tbl1, index = date)
test2= droplevels(test1)
# Error: `i` must evaluate to column positions or names, not a logical vector
```

**Comment by earowang** [comment]
I cannot reproduce the error you had. Perhaps it has been solved in the dev version.
``` r
library(tsibble)
#> 
#> Attaching package: 'tsibble'
#> The following object is masked from 'package:stats':
#> 
#>     filter
tbl1 <- tibble(
  date = as.Date("2017-01-01") + 0:9,
  thisfactor=factor(rep("A",10),levels=c("A","B")),
  value = rnorm(10)
)
test1 <- as_tsibble(tbl1, index = date)
test2 <- droplevels(test1)
test2
#> # A tsibble: 10 x 3 [1D]
#>    date       thisfactor   value
#>    <date>     <fct>        <dbl>
#>  1 2017-01-01 A          -0.188 
#>  2 2017-01-02 A          -1.07  
#>  3 2017-01-03 A           0.677 
#>  4 2017-01-04 A          -0.107 
#>  5 2017-01-05 A           1.97  
#>  6 2017-01-06 A           0.0162
#>  7 2017-01-07 A          -0.180 
#>  8 2017-01-08 A           2.40  
#>  9 2017-01-09 A           0.507 
#> 10 2017-01-10 A          -0.899
```

<sup>Created on 2019-02-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by derekholmes** [comment]
I checked, it was fixed in the development version.  I hope you can push that to production as soon as possible.

**Comment by earowang** [comment]
It was on CRAN yesterday.

**Comment by derekholmes** [comment]
thx much!
