### ISSUE TITLE
.fill in stretch_dbl

### ISSUE THREAD

**Issue by opoyc** [tidyverts/tsibble#88]
Having a tsibble, after creating a new variable with mutate, slice_dbl appends NA values to match the original number of rows, whereas stretch does not for .size=1.

x <- 1:10
slide_dbl(.x = x, .f = ~mean(.), .size = 2, .fill = NA)
stretch_dbl(.x = x, .f = ~mean(.), .init = 2, .fill = NA)

Am I missing something?

Nice package BTW!

**Comment by earowang** [comment]
The reason why no `.fill` in the `stretch()`, bc I'm not sure how to fill `NA` when the incrementing size is > 1. But I think I could add `NA` in the beginning of the each window size. I'll add `.fill = NA` for the `v0.7.0` release. Thanks.

**Comment by earowang** [comment]
Now `stretch()` gains a new argument `.fill = NA` to ensure the output of the same length as the input. But I renamed the argument `.size` to `.step`.
