### ISSUE TITLE
index_by() and spread()

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/tsibble#90]
As spread() is a row reducing function, perhaps this should interact with index_by().

Suppose you're interested in computing the difference between January and August for a time series (and you are only interested in this difference). With tsibble, you can get to the spread() operation before things get more difficult.
``` r
library(tsibble)
library(lubridate)
USAccDeaths %>% 
  as_tsibble %>% 
  mutate(month = month(index, label = TRUE)) %>% 
  filter(month %in% c("Jan", "Aug")) %>% 
  spread(month, value)
#> # A tsibble: 12 x 3 [1M]
#>       index   Jan   Aug
#>       <mth> <dbl> <dbl>
#>  1 1973 Jan  9007    NA
#>  2 1973 Aug    NA 10744
#>  3 1974 Jan  7750    NA
#>  4 1974 Aug    NA  9823
#>  5 1975 Jan  8162    NA
#>  6 1975 Aug    NA  9620
#>  7 1976 Jan  7717    NA
#>  8 1976 Aug    NA  9179
#>  9 1977 Jan  7792    NA
#> 10 1977 Aug    NA  9302
#> 11 1978 Jan  7836    NA
#> 12 1978 Aug    NA  9827
```

<sup>Created on 2019-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Using tibble, you can replace the index (leading to what would becomes a temporarily invalid tsibble), making this computation possible:

``` r
library(tsibble)
library(lubridate)
USAccDeaths %>% 
  as_tsibble %>% 
  as_tibble %>% 
  mutate(
    month = month(index, label = TRUE),
    index = year(index)
  ) %>% 
  filter(month %in% c("Jan", "Aug")) %>% 
  spread(month, value) %>% 
  mutate(Jan - Aug)
#> # A tibble: 6 x 4
#>   index   Jan   Aug `Jan - Aug`
#>   <dbl> <dbl> <dbl>       <dbl>
#> 1  1973  9007 10744       -1737
#> 2  1974  7750  9823       -2073
#> 3  1975  8162  9620       -1458
#> 4  1976  7717  9179       -1462
#> 5  1977  7792  9302       -1510
#> 6  1978  7836  9827       -1991
```

<sup>Created on 2019-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Perhaps a reasonable approach is to use index_by() to re-index after the spread() operation.
``` r
library(tsibble)
library(lubridate)
USAccDeaths %>% 
  as_tsibble %>% 
  mutate(month = month(index, label = TRUE)) %>% 
  filter(month %in% c("Jan", "Aug")) %>% 
  index_by(year = year(index)) %>% 
  spread(month, value) %>% 
  mutate(Jan - Aug)
#> # A tsibble: 6 x 4 [1Y]
#>   year    Jan   Aug `Jan - Aug`
#>   <dbl> <dbl> <dbl>       <dbl>
#> 1  1973  9007 10744       -1737
#> 2  1974  7750  9823       -2073
#> 3  1975  8162  9620       -1458
#> 4  1976  7717  9179       -1462
#> 5  1977  7792  9302       -1510
#> 6  1978  7836  9827       -1991
```

<sup>Created on 2019-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Thoughts?
One potential issue / source of confusion is that the original index has been replaced with the new index... but beyond that I think it could be useful.

**Comment by earowang** [comment]
The given example is currently not easy to achieve with tsibble, and the proposed approach looks fine. But can you give a more practical use case: what are you actually going to do with seasons placed as headers?

The example can also be produced (not exactly though, but more intuitively) as follows:

``` r
library(tsibble)
library(lubridate)
USAccDeaths %>% 
  as_tsibble %>% 
  mutate(month = month(index, label = TRUE)) %>% 
  filter(month %in% c("Jan", "Aug")) %>% 
  mutate(-difference(value))
#> # A tsibble: 12 x 4 [1M]
#>       index value month `-difference(value)`
#>       <mth> <dbl> <ord>                <dbl>
#>  1 1973 Jan  9007 Jan                     NA
#>  2 1973 Aug 10744 Aug                  -1737
#>  3 1974 Jan  7750 Jan                   2994
#>  4 1974 Aug  9823 Aug                  -2073
#>  5 1975 Jan  8162 Jan                   1661
#>  6 1975 Aug  9620 Aug                  -1458
#>  7 1976 Jan  7717 Jan                   1903
#>  8 1976 Aug  9179 Aug                  -1462
#>  9 1977 Jan  7792 Jan                   1387
#> 10 1977 Aug  9302 Aug                  -1510
#> 11 1978 Jan  7836 Jan                   1466
#> 12 1978 Aug  9827 Aug                  -1991
```

<sup>Created on 2019-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mitchelloharawild** [comment]
Useful when exploring the data. Check out slides 16-26 of https://github.com/robjhyndman/ETC3550Slides/blob/master/6-decomposition.pdf
Notably the difference is done to identify a much larger than usual drop in seasonal estimate.

This can probably also be done with `difference` as done above, and then a subsequent filter... but it may be less intuitive for some users. Still questioning this idea, but thought it would be worth mentioning.
