### ISSUE TITLE
format.yearweek and format.yearquarter return different output from Date for unrecognised format

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/tsibble#93]
When calling format() for `yearweek` and `yearquarter` with an unsupported format, it simply returns the requested format.
This is surprisingly not the same as `yearmonth`

``` r
library(tsibble)
#> 
#> Attaching package: 'tsibble'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
yearweek(Sys.Date()) %>% format("%x")
#> [1] "%x"
yearmonth(Sys.Date()) %>% format("%x")
#> [1] "01/02/19"
yearquarter(Sys.Date()) %>% format("%x")
#> [1] "%x"
```

<sup>Created on 2019-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by wfjvdham** [comment]
`yearmonth()` uses the `format()` of `Date` the other 2 not. That is why there is a difference in behavior. For consistency I think it would be better if they all use the `format()` of `Date`?

**Comment by mitchelloharawild** [comment]
`format()` for date classes doesn't support displays for quarters. Having these class methods isn't bad, although they should probably be passed through `format.POSIXct()` after performing the special parsing rules in `format.year[week/quarter]()`.
