### ISSUE TITLE
add index support for PCICt

### ISSUE THREAD

**Issue by adrfantini** [tidyverts/tsibble#94]
The default R calendar is fine for most users. Some of us, however, often use other types of calendars. For example, the [CF-Conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#calendar), which are used primarily by climate scientists, define the following possible calendars: `c('365', '365_day', 'noleap', '360', '360_day', 'gregorian', 'proleptic_gregorian', 'standard')`.
The R package `PCICt` (also used by the emerging pkg `stars`) provides a basic support for these calendars.

It would be awesome if `tsibble` somehow integrated support for other calendars.

**Comment by earowang** [comment]
I've never used the `PCICt` object. Can you please provide a data frame example that contains a column of `PCICt` and describe what interval you expect to see from the data frame? By looking at its documentation, it looks like a `POSIXct` but the printing method appears `Date`.  Is the underlying time unit "seconds" or "days"?

**Comment by adrfantini** [comment]
> I've never used the `PCICt` object. Can you please provide a data frame example that contains a column of `PCICt` and describe what interval you expect to see from the data frame? By looking at its documentation, it looks like a `POSIXct` but the printing method appears `Date`.

It appears that they cannot be coerced to a data.frame:
```
library(PCICt)
times = structure(c(778899600, 781491600, 784083600, 786675600, 789267600, 
791859600, 794451600, 797043600, 799635600, 802227600), cal = "360", months = c(30, 
30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30), dpy = 360, tzone = "GMT", units = "secs", class = "PCICt")

data.frame(times = times, var1 = runif(10), var2 = runif(10) + 7)
Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class ‘"PCICt"’ to a data.frame
```
I guess this is a limitation in `PCICt` that makes it impossible to integrate it in `tsibble`, right?

> Is the underlying time unit "seconds" or "days"?

As far as I understand it the the unit is `seconds`:
```
> str(times)
 'PCICt' num [1:10] 1995-01-16 01:00:00 1995-02-16 01:00:00 1995-03-16 01:00:00 1995-04-16 01:00:00 ...
 - attr(*, "cal")= chr "360"
 - attr(*, "months")= num [1:12] 30 30 30 30 30 30 30 30 30 30 ...
 - attr(*, "dpy")= num 360
 - attr(*, "tzone")= chr "GMT"
 - attr(*, "units")= chr "secs"
```

EDIT: Opened `PCICt` ticket https://github.com/pacificclimate/PCICt/issues/1

**Comment by earowang** [comment]
Seems that a vector underlies `PCICt`, not a list, and tibble naturally supports it. Do you expect the following example gives you an hour interval?

``` r
library(PCICt)
times <- as.PCICt(778899600, cal = "360", origin = "1970-01-01")
x <- times + seq(0, 60 * 60 * 9, by = 60 * 60)
tibble::tibble(times = x, var1 = runif(10), var2 = runif(10) + 7)
#> # A tibble: 10 x 3
#>    times                  var1  var2
#>    <S3: PCICt>           <dbl> <dbl>
#>  1 1995-01-16 01:00:00 0.878    7.95
#>  2 1995-01-16 02:00:00 0.303    7.72
#>  3 1995-01-16 03:00:00 0.552    7.74
#>  4 1995-01-16 04:00:00 0.718    7.86
#>  5 1995-01-16 05:00:00 0.223    7.85
#>  6 1995-01-16 06:00:00 0.647    7.10
#>  7 1995-01-16 07:00:00 0.713    7.38
#>  8 1995-01-16 08:00:00 0.493    7.86
#>  9 1995-01-16 09:00:00 0.515    7.62
#> 10 1995-01-16 10:00:00 0.00329  7.54
```

Would you be able to do a PR on this?

1. define `index_valid` for `PCICt`
https://github.com/tidyverts/tsibble/blob/896dbe9ef546ef9a0a1876d516603b6f0fd3a338/R/index-valid.R#L19-L21
2. define `pull_interval` for `PCICt` to compute expected interval
https://github.com/tidyverts/tsibble/blob/896dbe9ef546ef9a0a1876d516603b6f0fd3a338/R/interval.R#L35-L54

<sup>Created on 2019-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by adrfantini** [comment]
> Do you expect the following example gives you an hour interval?

`PCICt` AFAICT defines some arithmetic function so that adding `3600` seconds is always an hour (no matter the calendar); however I'm not sure that that was what you were asking. I suspect that I do not have a knowledge of `tsibble` sufficient to fully understand this question. This also means I'm doubtful in my ability to provide a suitable PR. Also, I have never done a GitHub PR and maybe I should start from something I understand fully.

**Comment by earowang** [comment]
You don't need to know deeply about `tsibble`, but more about how to calculate the interval from `PCICt`.

I suppose I don't have time to implement this feature, as I'm busy writing my thesis. You'll probably wait for several months, if I would implement this.

**Comment by adrfantini** [comment]
> You don't need to know deeply about `tsibble`, but more about how to calculate the interval from `PCICt`.
> 
> I suppose I don't have time to implement this feature, as I'm busy writing my thesis. You'll probably wait for several months, if I would implement this.

To be honest I'd like the time, but I do not know if I can find the time. If you have any particular resource re how to deal with intervals (e.g. does `tsibble` use intervals from `lubridate`?) please let me know.

Also, good luck with your thesis! I've just been there, too.

**Comment by earowang** [comment]
tsibble's interval is different from lubridate's interval. The resource is probably the source code that deals with the interval computing.
