### ISSUE TITLE
new function for cut time series

### ISSUE THREAD

**Issue by edvardoss** [tidyverts/tsibble#96]
Good day.
I often have to predict data that has significant gaps inside (after tsibble :: fill_gaps) and often very critical data gaps. For example, the retail network purchased products from us for 11 months, then 7 months in a row there were passes (closing the contract) and after the conclusion of the new contract (at different prices) sales started again (usually with a different trend and possibly with non-critical one-time voids). The only solution in such situations is to transfer to the forecasting model the final part of the time series following the last critical data break.
I think such situations are not uncommon in other industries, for example, a long gap in sensor readings is associated with readjustment of the equipment causing an impact on these sensors: the monthly lack of readings for sensors transmitting data daily may be due to the installation of new climate equipment giving a completely different statistics after the resumption of sensors . And here it is also a solution to take into use the residual part of the data of the voids following the last critical interval.
I always work with a large number of time series at the same time (thousands and tens of thousands embedded in the data frame) and there is no possibility to track such situations for each series, so I wrote a custom function that I pass to the purrr immediately after fill_gaps. I think it will be useful to many users and I would be glad if you included it in one form or another in your package.
Below I give the function code and an example of its operation on the airquality data set built in R.
Anyway, thanks for the great package!

---

```r
fn_KeepDataAfterLastEmptyWindow   <- function(dfr, NAs.FieldName ,MinEmptyWidthToSearch){
--
# dfr -  data frame that is pre-ordered (for example, by date)
# NAs.FieldName -text field name analysis of missing values
# MinEmptyWidthToSearch - the minimum width of the window skips for inclusion in the search
stopifnot(MinEmptyWidthToSearch>1,!is.na(NAs.FieldName))
NAs.FieldName <- as.symbol(NAs.FieldName)
require(dplyr)
dfr %>%   mutate(na.start=is.na(!!NAs.FieldName)&!is.na(lag(!!NAs.FieldName)),na.chain.id=cumsum(na.start))   %>%
group_by(na.chain.id) %>%   mutate(na.count=sum(is.na(!!NAs.FieldName))) %>% ungroup %>%
mutate(cut.flag=is.na(!!NAs.FieldName)&(na.count>=MinEmptyWidthToSearch))   %>%
mutate(cut.flag.id=if_else(cut.flag,row_number(),0L)) %>% # для   того что бы выбрать последнее окно если несколько одинаковых максимумов   пустот
filter(row_number()>max(cut.flag.id)) %>%   select(-na.start,-na.chain.id, -na.count, -cut.flag, -cut.flag.id)   %>%
return(.)
}

airquality %>% View() 
library(magrittr)
# if we take for the minimum analysis window = 2, then we see that the last such window on Ozone is August 10-11
fn_KeepDataAfterLastEmptyWindow(dfr = airquality,NAs.FieldName = "Ozone",MinEmptyWidthToSearch = 2) %>% 
  View() # we see that the function displays Ozone statistics since August 12, without windows with NA from 2 consecutive observations

# if we take the minimum width of the analysis window = 3 then we remove from the analysis all the data until the last big pass from June 21 to June 30
fn_KeepDataAfterLastEmptyWindow(dfr = airquality,NAs.FieldName = "Ozone",MinEmptyWidthToSearch = 3) %>% 
  View()

```

**Comment by earowang** [comment]
I don't quite understand what you attempt to do. Do you want to count how many runs of `NA` in the data and then subset the last bit of data conditional on the threshold of the number of `NA`?

In this case, you don't need to fill gaps with `NA` using `fill_gaps()` first. Can you use [`count_gaps()`](https://tsibble.tidyverts.org/reference/count_gaps.html) to get how many gaps in your data, and then subset?

**Comment by edvardoss** [comment]
the goal is to keep that part of the time series that follows the last NA sequence longer than the minimum threshold of the length of the NA value set by the user.
The proposed function count _gaps may slightly simplify the code but will not do what is required to the end, although I like the idea behind count _gaps.

**Comment by earowang** [comment]
`count_gaps()` will not lead to the end of what is required, but does most of it. The rest is combining `slice()` and `filter()`, which is straightforward. Thanks for the suggestion.
